/**
 * Workflow Templates
 * Pre-built workflow templates for common PDF processing tasks
 */

import { WorkflowTemplate } from '@/types/workflow';

export const workflowTemplates: WorkflowTemplate[] = [
    {
        id: 'merge-compress',
        name: 'Merge & Compress',
        description: 'Merge multiple PDFs and compress the result for smaller file size',
        category: 'common',
        nodes: [
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'merge-1',
                target: 'compress-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'images-to-pdf-watermark',
        name: 'Images to Watermarked PDF',
        description: 'Convert images to PDF and add a custom watermark',
        category: 'conversion',
        nodes: [
            {
                id: 'image-to-pdf-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'image-to-pdf',
                    label: 'Image to PDF',
                    icon: 'images',
                    category: 'convert-to-pdf',
                    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.bmp', '.tiff', '.tif', '.svg', '.heic'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'image-to-pdf-1',
                target: 'watermark-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'pdf-to-images-compress',
        name: 'PDF to Compressed Images',
        description: 'Convert PDF pages to JPG images',
        category: 'conversion',
        nodes: [
            {
                id: 'pdf-to-jpg-1',
                type: 'toolNode',
                position: { x: 250, y: 200 },
                data: {
                    toolId: 'pdf-to-jpg',
                    label: 'PDF to JPG',
                    icon: 'file-image',
                    category: 'convert-from-pdf',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'jpg',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'secure-pdf',
        name: 'Create Secure PDF',
        description: 'Merge PDFs, add watermark, and encrypt with password',
        category: 'security',
        nodes: [
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'encrypt-1',
                type: 'toolNode',
                position: { x: 700, y: 200 },
                data: {
                    toolId: 'encrypt-pdf',
                    label: 'Encrypt PDF',
                    icon: 'lock',
                    category: 'security-privacy',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'merge-1',
                target: 'watermark-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'watermark-1',
                target: 'encrypt-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'document-prep',
        name: 'Document Preparation',
        description: 'Merge PDFs, add page numbers, and add header/footer',
        category: 'common',
        nodes: [
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'page-numbers-1',
                type: 'toolNode',
                position: { x: 400, y: 150 },
                data: {
                    toolId: 'page-numbers',
                    label: 'Add Page Numbers',
                    icon: 'list-ordered',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'header-footer-1',
                type: 'toolNode',
                position: { x: 700, y: 150 },
                data: {
                    toolId: 'header-footer',
                    label: 'Add Header/Footer',
                    icon: 'pilcrow',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'merge-1',
                target: 'page-numbers-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'page-numbers-1',
                target: 'header-footer-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'optimize-for-web',
        name: 'Optimize for Web',
        description: 'Compress and linearize PDF for fast web viewing',
        category: 'optimization',
        nodes: [
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'linearize-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'linearize-pdf',
                    label: 'Linearize PDF',
                    icon: 'zap-off',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'compress-1',
                target: 'linearize-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'split-and-watermark',
        name: 'Split & Watermark',
        description: 'Split PDF into pages and add watermark to each',
        category: 'common',
        nodes: [
            {
                id: 'split-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'split-pdf',
                    label: 'Split PDF',
                    icon: 'scissors',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'split-1',
                target: 'watermark-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'office-to-pdf-merge',
        name: 'Office Files to Single PDF',
        description: 'Convert Word documents to PDF and merge them',
        category: 'conversion',
        nodes: [
            {
                id: 'word-to-pdf-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'word-to-pdf',
                    label: 'Word to PDF',
                    icon: 'file-text',
                    category: 'convert-to-pdf',
                    acceptedFormats: ['.doc', '.docx'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'word-to-pdf-1',
                target: 'merge-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'rotate-and-number',
        name: 'Rotate & Add Page Numbers',
        description: 'Rotate PDF pages and add page numbers',
        category: 'common',
        nodes: [
            {
                id: 'rotate-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'rotate-pdf',
                    label: 'Rotate PDF',
                    icon: 'rotate-cw',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'page-numbers-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'page-numbers',
                    label: 'Add Page Numbers',
                    icon: 'list-ordered',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'rotate-1',
                target: 'page-numbers-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'print-ready',
        name: 'Print Ready Document',
        description: 'Prepare PDF for printing with page numbers and flatten',
        category: 'common',
        nodes: [
            {
                id: 'page-numbers-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'page-numbers',
                    label: 'Add Page Numbers',
                    icon: 'list-ordered',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'flatten-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'flatten-pdf',
                    label: 'Flatten PDF',
                    icon: 'layers',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'page-numbers-1',
                target: 'flatten-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'grayscale-compress',
        name: 'Grayscale & Compress',
        description: 'Convert to grayscale and compress for smaller size',
        category: 'optimization',
        nodes: [
            {
                id: 'grayscale-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'pdf-to-greyscale',
                    label: 'Convert to Grayscale',
                    icon: 'palette',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'grayscale-1',
                target: 'compress-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'extract-and-merge',
        name: 'Extract & Merge Pages',
        description: 'Extract specific pages and merge them into a new document',
        category: 'common',
        nodes: [
            {
                id: 'extract-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'extract-pages',
                    label: 'Extract Pages',
                    icon: 'copy',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'extract-1',
                target: 'merge-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'confidential-document',
        name: 'Confidential Document',
        description: 'Add confidential watermark and encrypt PDF',
        category: 'security',
        nodes: [
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                    settings: {
                        text: 'CONFIDENTIAL',
                        opacity: 0.3,
                    },
                },
            },
            {
                id: 'encrypt-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'encrypt-pdf',
                    label: 'Encrypt PDF',
                    icon: 'lock',
                    category: 'security-privacy',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'watermark-1',
                target: 'encrypt-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'pdf-to-docx-cleanup',
        name: 'PDF to Editable Document',
        description: 'Convert PDF to Word document for editing',
        category: 'conversion',
        nodes: [
            {
                id: 'pdf-to-docx-1',
                type: 'toolNode',
                position: { x: 250, y: 200 },
                data: {
                    toolId: 'pdf-to-docx',
                    label: 'PDF to Word',
                    icon: 'file-text',
                    category: 'convert-from-pdf',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'docx',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'comprehensive-optimization',
        name: 'Full Document Optimization',
        description: 'Compress, flatten, and linearize for optimal performance',
        category: 'optimization',
        nodes: [
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'flatten-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'flatten-pdf',
                    label: 'Flatten PDF',
                    icon: 'layers',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'linearize-1',
                type: 'toolNode',
                position: { x: 700, y: 200 },
                data: {
                    toolId: 'linearize-pdf',
                    label: 'Linearize PDF',
                    icon: 'zap-off',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'compress-1',
                target: 'flatten-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'flatten-1',
                target: 'linearize-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'pdf-to-presentation',
        name: 'PDF to PowerPoint',
        description: 'Convert PDF to editable PowerPoint presentation',
        category: 'conversion',
        nodes: [
            {
                id: 'pdf-to-pptx-1',
                type: 'toolNode',
                position: { x: 250, y: 200 },
                data: {
                    toolId: 'pdf-to-pptx',
                    label: 'PDF to PowerPoint',
                    icon: 'presentation',
                    category: 'convert-from-pdf',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pptx',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'unlock-and-edit',
        name: 'Unlock & Edit PDF',
        description: 'Decrypt protected PDF for editing',
        category: 'security',
        nodes: [
            {
                id: 'decrypt-1',
                type: 'toolNode',
                position: { x: 250, y: 200 },
                data: {
                    toolId: 'decrypt-pdf',
                    label: 'Decrypt PDF',
                    icon: 'unlock',
                    category: 'security-privacy',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'crop-and-resize',
        name: 'Crop & Resize Pages',
        description: 'Crop PDF pages and adjust page dimensions',
        category: 'common',
        nodes: [
            {
                id: 'crop-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'crop-pdf',
                    label: 'Crop PDF',
                    icon: 'crop',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'resize-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'fix-page-size',
                    label: 'Fix Page Size',
                    icon: 'ruler',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'crop-1',
                target: 'resize-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'ebook-convert',
        name: 'eBook to PDF',
        description: 'Convert EPUB eBooks to PDF format',
        category: 'conversion',
        nodes: [
            {
                id: 'epub-to-pdf-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'epub-to-pdf',
                    label: 'EPUB to PDF',
                    icon: 'book-open',
                    category: 'convert-to-pdf',
                    acceptedFormats: ['.epub'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'epub-to-pdf-1',
                target: 'compress-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'batch-watermark',
        name: 'Batch Watermark',
        description: 'Add watermark to multiple PDF files at once',
        category: 'common',
        nodes: [
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 250, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                    settings: {
                        text: 'WATERMARK',
                        opacity: 0.3,
                    },
                },
            },
        ],
        edges: [],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'archive-prep',
        name: 'Archive Preparation',
        description: 'Remove metadata, flatten, and compress for long-term storage',
        category: 'optimization',
        nodes: [
            {
                id: 'remove-metadata-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'remove-metadata',
                    label: 'Remove Metadata',
                    icon: 'file-minus',
                    category: 'security-privacy',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'flatten-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'flatten-pdf',
                    label: 'Flatten PDF',
                    icon: 'layers',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 700, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'remove-metadata-1',
                target: 'flatten-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'flatten-1',
                target: 'compress-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'report-assembly',
        name: 'Report Assembly',
        description: 'Merge documents, add page numbers, header/footer and table of contents',
        category: 'common',
        nodes: [
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'page-numbers-1',
                type: 'toolNode',
                position: { x: 400, y: 150 },
                data: {
                    toolId: 'page-numbers',
                    label: 'Add Page Numbers',
                    icon: 'list-ordered',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'header-footer-1',
                type: 'toolNode',
                position: { x: 700, y: 150 },
                data: {
                    toolId: 'header-footer',
                    label: 'Add Header/Footer',
                    icon: 'pilcrow',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'toc-1',
                type: 'toolNode',
                position: { x: 1000, y: 150 },
                data: {
                    toolId: 'table-of-contents',
                    label: 'Add Table of Contents',
                    icon: 'list',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'merge-1',
                target: 'page-numbers-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'page-numbers-1',
                target: 'header-footer-1',
                isValid: true,
            },
            {
                id: 'edge-3',
                source: 'header-footer-1',
                target: 'toc-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'invoice-processing',
        name: 'Invoice Processing',
        description: 'Extract pages, add watermark, and compress for email',
        category: 'common',
        nodes: [
            {
                id: 'extract-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'extract-pages',
                    label: 'Extract Pages',
                    icon: 'copy',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 700, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'extract-1',
                target: 'watermark-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'watermark-1',
                target: 'compress-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'photo-album',
        name: 'Photo Album Creator',
        description: 'Convert images to PDF with page numbers',
        category: 'conversion',
        nodes: [
            {
                id: 'image-to-pdf-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'image-to-pdf',
                    label: 'Image to PDF',
                    icon: 'images',
                    category: 'convert-to-pdf',
                    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.bmp', '.tiff', '.tif', '.svg', '.heic'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'page-numbers-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'page-numbers',
                    label: 'Add Page Numbers',
                    icon: 'list-ordered',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'image-to-pdf-1',
                target: 'page-numbers-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
];

export const getTemplatesByCategory = (category: WorkflowTemplate['category']) => {
    return workflowTemplates.filter(t => t.category === category);
};

export const getTemplateById = (id: string) => {
    return workflowTemplates.find(t => t.id === id);
};
