/**
 * Interactive Form Logic Designer Processor
 * Parses AcroForm fields and injects Acrobat JavaScript (AcroJS) to enable dynamic field dependencies.
 */

import type {
  ProcessInput,
  ProcessOutput,
  ProgressCallback,
} from '@/types/pdf';
import { PDFErrorCode } from '@/types/pdf';
import { BasePDFProcessor } from '../processor';
import { loadPdfLib } from '../loader';

export interface FormLogicRule {
  source: string; // Source field name
  trigger: 'change' | 'blur';
  condition: 'equals' | 'not-equals' | 'checked' | 'unchecked';
  value?: string;
  target: string; // Target field name
  action: 'show' | 'hide' | 'enable' | 'disable' | 'setValue';
  actionValue?: string;
}

export interface FormLogicOptions {
  rules: FormLogicRule[];
}

export class FormLogicDesignerProcessor extends BasePDFProcessor {
  async process(
    input: ProcessInput,
    onProgress?: ProgressCallback
  ): Promise<ProcessOutput> {
    this.reset();
    this.onProgress = onProgress;

    const { files, options } = input;
    const designerOptions: FormLogicOptions = {
      rules: [],
      ...(options as Partial<FormLogicOptions>),
    };

    if (files.length !== 1) {
      return this.createErrorOutput(
        PDFErrorCode.INVALID_OPTIONS,
        'Exactly one PDF file is required.'
      );
    }

    const file = files[0];

    try {
      this.updateProgress(10, 'Loading pdf-lib engine...');
      const pdfLib = await loadPdfLib();

      this.updateProgress(20, 'Loading interactive PDF Form layers...');
      const arrayBuffer = await file.arrayBuffer();
      const pdfDoc = await pdfLib.PDFDocument.load(arrayBuffer);
      const form = pdfDoc.getForm();
      const fields = form.getFields();

      if (fields.length === 0) {
        return this.createErrorOutput(
          PDFErrorCode.INVALID_OPTIONS,
          'This PDF does not contain any AcroForm interactive fields. Please create fields first.'
        );
      }

      this.updateProgress(45, 'Compiling node rules into Acrobat JS (AcroJS)...');
      
      // Group rules by source field to inject consolidated scripts
      const rulesBySource: Record<string, FormLogicRule[]> = {};
      designerOptions.rules.forEach(rule => {
        if (!rulesBySource[rule.source]) {
          rulesBySource[rule.source] = [];
        }
        rulesBySource[rule.source].push(rule);
      });

      this.updateProgress(65, 'Injecting AcroJS Action streams into PDF objects...');

      // Inject AcroJS into source fields
      for (const sourceFieldName of Object.keys(rulesBySource)) {
        const rules = rulesBySource[sourceFieldName];
        const field = fields.find(f => f.getName() === sourceFieldName);

        if (!field) {
          console.warn(`Source field not found: ${sourceFieldName}`);
          continue;
        }

        // Generate JavaScript code for these rules
        let jsCode = `// Generated by EasyPDFNex Form Logic Designer\n`;
        jsCode += `var srcVal = event.value;\n`;

        rules.forEach(rule => {
          let condStr = '';
          if (rule.condition === 'checked') {
            condStr = `srcVal === "Yes" || srcVal === true || srcVal === "On"`;
          } else if (rule.condition === 'unchecked') {
            condStr = `srcVal === "Off" || srcVal === false || !srcVal`;
          } else if (rule.condition === 'equals') {
            condStr = `srcVal === "${escapeJsString(rule.value || '')}"`;
          } else if (rule.condition === 'not-equals') {
            condStr = `srcVal !== "${escapeJsString(rule.value || '')}"`;
          }

          let actionStr = '';
          if (rule.action === 'show') {
            actionStr = `tgt.display = display.visible;`;
          } else if (rule.action === 'hide') {
            actionStr = `tgt.display = display.hidden;`;
          } else if (rule.action === 'enable') {
            actionStr = `tgt.readonly = false;`;
          } else if (rule.action === 'disable') {
            actionStr = `tgt.readonly = true;`;
          } else if (rule.action === 'setValue') {
            actionStr = `tgt.value = "${escapeJsString(rule.actionValue || '')}";`;
          }

          jsCode += `try {\n`;
          jsCode += `  var tgt = this.getField("${escapeJsString(rule.target)}");\n`;
          jsCode += `  if (tgt) {\n`;
          jsCode += `    if (${condStr}) {\n`;
          jsCode += `      ${actionStr}\n`;
          jsCode += `    }\n`;
          jsCode += `  }\n`;
          jsCode += `} catch(e) { console.println(e); }\n`;
        });

        // Inject using pdf-lib direct dictionary manipulation
        const fieldDict = field.acroField.dict;
        const context = pdfDoc.context;

        // Build Javascript action object
        // JS must be represented as a PDFString or PDFStream
        const jsAction = context.obj({
          S: pdfLib.PDFName.of('JavaScript'),
          JS: pdfLib.PDFString.of(jsCode),
        });

        // AA dictionary (Additional Actions)
        // V: Validate, K: Keystroke, etc.
        // For inputs/checkboxes, Validate is the most robust event for values
        const aaDict = context.obj({
          V: jsAction,
        });

        fieldDict.set(pdfLib.PDFName.of('AA'), aaDict);
      }

      this.updateProgress(85, 'Serializing customized PDF...');
      const pdfBytes = await pdfDoc.save();
      const outputBlob = new Blob([pdfBytes as any], { type: 'application/pdf' });
      const outputFilename = file.name.replace(/\.pdf$/i, '_smart.pdf');

      this.updateProgress(100, 'Form logic injection complete!');
      return this.createSuccessOutput(outputBlob, outputFilename, {
        fieldsCount: fields.length,
        rulesCount: designerOptions.rules.length,
      });

    } catch (error) {
      return this.createErrorOutput(
        PDFErrorCode.PROCESSING_FAILED,
        'Failed to design and inject form logic.',
        error instanceof Error ? error.message : 'Unknown error'
      );
    }
  }

  protected getAcceptedTypes(): string[] {
    return ['application/pdf'];
  }
}

// Simple JS string escaper
function escapeJsString(val: string): string {
  return val.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

export function createFormLogicDesignerProcessor(): FormLogicDesignerProcessor {
  return new FormLogicDesignerProcessor();
}

export async function injectFormLogic(
  file: File,
  options?: Partial<FormLogicOptions>,
  onProgress?: ProgressCallback
): Promise<ProcessOutput> {
  const processor = createFormLogicDesignerProcessor();
  return processor.process(
    {
      files: [file],
      options: options || { rules: [] },
    },
    onProgress
  );
}
