import json

translations = {
  "ja": {
    "tools.cropPdf.page": "ページ",
    "tools.extractImages.page": "ページ",
    "tools.rotatePdf.angle": "回転角度",
    "tools.combineSinglePage.orientation": "ページの方向",
    "tools.txtToPdf.orientation": "ページの方向",
    "tools.txtToPdf.portrait": "縦向き",
    "tools.pdfToSvg.previewPage": "対象ページ",
    "tools.pageDimensions.page": "ページ",
    "tools.pageDimensions.orientation": "方向",
    "tools.removeRestrictions.optionsTitle": "オプション設定",
    "tools.fixPageSize.orientPortrait": "縦向き",
    "tools.bookmark.page": "対象ページ",
    "tools.bookmark.style": "スタイル",
    "tools.pageNumbers.styleTitle": "フォントスタイル",
    "tools.pageNumbers.style": "スタイル",
    "tools.pageNumbers.oddPositionHint": "ページ 1, 3, 5...",
    "tools.pageNumbers.evenPositionHint": "ページ 2, 4, 6...",
    "tools.watermark.type": "透かしタイプ",
    "tools.watermark.angle": "配置角度",
    "tools.headerFooter.styleTitle": "フォントスタイル",
    "tools.formCreator.pageNavigation": "ページ {current} / {total}",
    "tools.formCreator.fieldType": "フィールドタイプ",
    "tools.formCreator.page": "ページ {number}",
    "tools.formCreator.signatureTool": "署名",
    "tools.formCreator.dateTool": "日付",
    "tools.formCreator.optionsTab": "オプション",
    "tools.formCreator.pages": "ページ数",
    "tools.removeBlankPages.page": "ページ {number}",
    "tools.pdfBooklet.orientationLabel": "用紙の向き",
    "tools.fontToOutline.optionsTitle": "オプション",
    "tools.findAndRedact.pageNumber": "第 {page} ページ",
    "tools.findAndRedact.pageInfo": "第 {page} ページ",
    "common.buttons.edit": "編集",
    "common.globalInvoiceParser.uploadLabel": "外貨インボイス（発票）PDFのアップロード",
    "common.globalInvoiceParser.uploadDescription": "インボイスの金額情報をインテリジェントに分析し、ローカルで為替レートを自動換算します。美しくデザインされた現地通貨への換算・記帳カードをレンダリングします。",
    "common.globalInvoiceParser.optionsTitle": "グローバルインボイス為替換算設定",
    "common.globalInvoiceParser.processButton": "インボイス分析＆為替換算を実行",
    "common.globalInvoiceParser.successMessage": "外貨インボイスに為替換算記帳スタンプが正常に適用されました！",
    "common.globalInvoiceParser.previewTitle": "インボイス為替換算の記帳プレビュー",
    "common.globalInvoiceParser.convertedSuccess": "為替換算成功",
    "common.globalInvoiceParser.convertRateApplied": "為替レート {rate} に基づき、元の総額 {original} {currency} を現地通貨に正常に換算しました。",
    "common.globalInvoiceParser.emptyStateDescription": "ワンクリックでインボイスから通貨と金額の情報を自動で抽出し、美しくデザインされたグラスモーフィズム調の現地通貨記帳カードをローカルにレンダリングします。",
    "common.globalInvoiceParser.targetCurrencyLabel": "換算対象（本位）通貨",
    "common.globalInvoiceParser.customRateLabel": "カスタム為替レート (任意)",
    "common.globalInvoiceParser.customRatePlaceholder": "例: 7.25 (未入力の場合はデフォルトでリアルタイム為替レートを使用)",
    "contactPage.methods.email.title": "メールアドレス",
    "contactPage.form.fields.email.label": "メールアドレス",
    "tools.pdfMultiTool.uploadDescription": "PDFファイルをここにドラッグ＆ドロップするか、クリックして選択してください。複数のファイルをアップロードできます。",
    "tools.pdfMultiTool.addMoreFiles": "PDFファイルを追加",
    "tools.pdfMultiTool.organize": "整理",
    "tools.pdfMultiTool.rotate": "回転",
    "tools.pdfMultiTool.duplicate": "複製",
    "tools.pdfMultiTool.addBlank": "空白ページの追加",
    "tools.pdfMultiTool.organizeHint": "ページをドラッグ＆ドロップして並べ替えます。",
    "tools.pdfMultiTool.deleteHint": "ページをクリックすると、削除対象としてマークされます。",
    "tools.pdfMultiTool.rotateHint": "ページ内の回転ボタンをクリックするか、すべてのページを一括で回転します：",
    "tools.pdfMultiTool.duplicateHint": "ページ上の複製ボタンをクリックすると、そのページがコピーされます。",
    "tools.pdfMultiTool.reset": "リセット",
    "tools.pdfMultiTool.undo": "元に戻す",
    "tools.pdfMultiTool.redo": "やり直し",
    "tools.pdfMultiTool.deselectAll": "選択解除",
    "tools.pdfMultiTool.exportPDF": "PDFを出力する",
    "tools.pdfMultiTool.downloadSelected": "選択したページをダウンロード",
    "tools.pdfMultiTool.addBlankPageTitle": "空白ページの追加",
    "tools.pdfMultiTool.numberOfPages": "追加するページ数",
    "tools.pdfMultiTool.insertPosition": "挿入位置",
    "tools.pdfMultiTool.processButton": "変更を適用する",
    "tools.pdfMultiTool.successMessage": "PDFの処理が正常に完了しました！「ダウンロード」ボタンをクリックしてファイルを保存してください。",
    "tools.editMetadata.resetButton": "リセット",
    "tools.imageToPdf.fitToImage": "画像サイズに合わせる",
    "tools.imageToPdf.margin": "余白",
    "tools.imageToPdf.batchMode": "複数のPDFに分割出力する",
    "tools.imageToPdf.imagesPerPdf": "PDFあたりの画像数",
    "tools.imageToPdf.batchModeHint": "{pdfCount}個のPDFファイルが作成され、ZIP形式で圧縮・アーカイブされます。",
    "tools.imageToPdf.batchSuccessMessage": "{imageCount}枚の画像から{pdfCount}個のPDFファイルが正常に作成されました！「ダウンロード」ボタンをクリックしてZIPファイルを保存してください。",
    "tools.compressPdf.algorithmLabel": "圧縮アルゴリズム",
    "tools.compressPdf.algorithmCondense": "深度圧縮",
    "tools.compressPdf.algorithmStandardDesc": "オブジェクトストリームを使用した汎用的な標準圧縮を行います。ファイルサイズとドキュメント品質のバランスを最適化します。",
    "tools.compressPdf.algorithmCondenseDesc": "対話型要素（リンクやフォーム等）を維持しつつ、PDFの内部データ構造を高度に圧縮して最適化します。",
    "tools.compressPdf.algorithmPhotonDesc": "各ページを画像として高品質ラスタライズします。画像の多いPDFで極限までファイルサイズを小さくしたい場合に最適です。"
  },
  "ko": {
    "tools.cropPdf.page": "페이지",
    "tools.extractImages.page": "페이지",
    "tools.rotatePdf.angle": "회전 각도",
    "tools.combineSinglePage.orientation": "용지 방향",
    "tools.txtToPdf.orientation": "용지 방향",
    "tools.txtToPdf.portrait": "세로 방향",
    "tools.pdfToSvg.previewPage": "해당 페이지",
    "tools.pageDimensions.page": "페이지",
    "tools.pageDimensions.orientation": "방향",
    "tools.removeRestrictions.optionsTitle": "옵션 설정",
    "tools.fixPageSize.orientPortrait": "세로 방향",
    "tools.bookmark.page": "해당 페이지",
    "tools.bookmark.style": "스타일",
    "tools.pageNumbers.styleTitle": "글꼴 스타일",
    "tools.pageNumbers.style": "스타일",
    "tools.pageNumbers.oddPositionHint": "페이지 1, 3, 5...",
    "tools.pageNumbers.evenPositionHint": "페이지 2, 4, 6...",
    "tools.watermark.type": "워터마크 유형",
    "tools.watermark.angle": "회전 각도",
    "tools.headerFooter.styleTitle": "글꼴 스타일",
    "tools.formCreator.pageNavigation": "페이지 {current} / {total}",
    "tools.formCreator.fieldType": "필드 유형",
    "tools.formCreator.page": "페이지 {number}",
    "tools.formCreator.signatureTool": "서명",
    "tools.formCreator.dateTool": "날짜",
    "tools.formCreator.optionsTab": "옵션",
    "tools.formCreator.pages": "페이지 수",
    "tools.removeBlankPages.page": "페이지 {number}",
    "tools.pdfBooklet.orientationLabel": "용지 방향",
    "tools.fontToOutline.optionsTitle": "옵션",
    "tools.findAndRedact.pageNumber": "제 {page} 페이지",
    "tools.findAndRedact.pageInfo": "제 {page} 페이지",
    "common.buttons.edit": "편집",
    "common.globalInvoiceParser.uploadLabel": "외화 송장(인보이스) PDF 업로드",
    "common.globalInvoiceParser.uploadDescription": "송장 금액을 지능적으로 인식하여 로컬에서 환율을 자동으로 환산하고, 세련된 디자인의 원화 환산 기입 카드를 적용합니다.",
    "common.globalInvoiceParser.optionsTitle": "외화 송장 환산 설정",
    "common.globalInvoiceParser.processButton": "송장 분석 및 환산 실행",
    "common.globalInvoiceParser.successMessage": "외화 송장에 환산 장부 스탬프가 성공적으로 찍혔습니다!",
    "common.globalInvoiceParser.previewTitle": "송장 환산 기입 미리보기",
    "common.globalInvoiceParser.convertedSuccess": "환산 완료",
    "common.globalInvoiceParser.convertRateApplied": "환율 {rate}을 적용하여 원래 총액 {original} {currency}을 성공적으로 환산 완료하였습니다.",
    "common.globalInvoiceParser.emptyStateDescription": "원클릭으로 송장의 통화와 금액을 자동으로 추출하여 입체감 있는 유리 질감(Glassmorphism) 스타일의 환산 기입 카드를 웹 브라우저 내에 렌더링합니다.",
    "common.globalInvoiceParser.targetCurrencyLabel": "목표 기준 통화",
    "common.globalInvoiceParser.customRateLabel": "사용자 정의 환율 (선택)",
    "common.globalInvoiceParser.customRatePlaceholder": "예: 7.25 (공란으로 둘 경우 기본 실시간 환율을 반영합니다)",
    "contactPage.methods.email.title": "이메일 주소",
    "contactPage.form.fields.email.label": "이메일 주소",
    "tools.pdfMultiTool.uploadDescription": "PDF 파일을 여기에 드래그 앤 드롭하거나 클릭하여 선택하십시오. 여러 파일을 한 번에 업로드할 수 있습니다.",
    "tools.pdfMultiTool.addMoreFiles": "PDF 파일 더 추가하기",
    "tools.pdfMultiTool.organize": "정렬",
    "tools.pdfMultiTool.rotate": "회전",
    "tools.pdfMultiTool.duplicate": "복제",
    "tools.pdfMultiTool.addBlank": "빈 페이지 추가",
    "tools.pdfMultiTool.organizeHint": "페이지를 드래그 앤 드롭하여 순서를 변경하십시오.",
    "tools.pdfMultiTool.deleteHint": "삭제할 페이지를 클릭하여 표시해 주십시오.",
    "tools.pdfMultiTool.rotateHint": "페이지의 회전 단추를 클릭하거나 전체 회전을 조절하십시오:",
    "tools.pdfMultiTool.duplicateHint": "페이지의 복제 버튼을 클릭하여 복사하십시오.",
    "tools.pdfMultiTool.reset": "초기화",
    "tools.pdfMultiTool.undo": "실행 취소",
    "tools.pdfMultiTool.redo": "다시 실행",
    "tools.pdfMultiTool.deselectAll": "선택 해제",
    "tools.pdfMultiTool.exportPDF": "PDF 내보내기",
    "tools.pdfMultiTool.downloadSelected": "선택 항목 다운로드",
    "tools.pdfMultiTool.addBlankPageTitle": "빈 페이지 추가",
    "tools.pdfMultiTool.numberOfPages": "추가할 페이지 수",
    "tools.pdfMultiTool.insertPosition": "삽입할 위치",
    "tools.pdfMultiTool.processButton": "변경 사항 적용",
    "tools.pdfMultiTool.successMessage": "PDF 처리가 성공적으로 끝났습니다! 다운로드 버튼을 눌러 파일을 컴퓨터에 저장하십시오.",
    "tools.editMetadata.resetButton": "초기화",
    "tools.imageToPdf.fitToImage": "이미지 크기에 맞춤",
    "tools.imageToPdf.margin": "여백",
    "tools.imageToPdf.batchMode": "여러 PDF로 분할 생성",
    "tools.imageToPdf.imagesPerPdf": "PDF당 이미지 개수",
    "tools.imageToPdf.batchModeHint": "{pdfCount}개의 PDF 파일이 생성되며, 하나의 ZIP 압축 파일로 묶어서 저장됩니다.",
    "tools.imageToPdf.batchSuccessMessage": "{imageCount}개의 이미지로부터 {pdfCount}개의 PDF 파일을 성공적으로 생성하였습니다! 다운로드 버튼을 클릭해 ZIP 압축 파일을 보관하십시오.",
    "tools.compressPdf.algorithmLabel": "압축 알고리즘",
    "tools.compressPdf.algorithmCondense": "딥 압축",
    "tools.compressPdf.algorithmStandardDesc": "객체 스트림을 사용하는 표준 범용 압축을 실행합니다. 품질 손상 없이 파일 용량을 균형 있게 축소합니다.",
    "tools.compressPdf.algorithmCondenseDesc": "대화형 요소(하이퍼링크, 폼 필드 등)의 동작은 보존하면서 내부 데이터 구조를 딥 압축해 용량을 최소화합니다.",
    "tools.compressPdf.algorithmPhotonDesc": "모든 페이지를 래스터화(이미지화) 방식으로 고화질 변환합니다. 다량의 이미지가 삽입된 대용량 PDF 문서의 압축에 최적입니다."
  },
  "de": {
    "tools.cropPdf.page": "Seite",
    "tools.extractImages.page": "Seite",
    "tools.rotatePdf.angle": "Winkel",
    "tools.combineSinglePage.orientation": "Ausrichtung",
    "tools.txtToPdf.orientation": "Ausrichtung",
    "tools.txtToPdf.portrait": "Hochformat",
    "tools.pdfToSvg.previewPage": "Seite",
    "tools.pageDimensions.page": "Seite",
    "tools.pageDimensions.orientation": "Ausrichtung",
    "tools.removeRestrictions.optionsTitle": "Optionen",
    "tools.fixPageSize.orientPortrait": "Hochformat",
    "tools.bookmark.page": "Seite",
    "tools.bookmark.style": "Stil",
    "tools.pageNumbers.styleTitle": "Stil",
    "tools.pageNumbers.style": "Stil",
    "tools.pageNumbers.oddPositionHint": "Seiten 1, 3, 5...",
    "tools.pageNumbers.evenPositionHint": "Seiten 2, 4, 6...",
    "tools.watermark.type": "Wasserzeichentyp",
    "tools.watermark.angle": "Winkel",
    "tools.headerFooter.styleTitle": "Stil",
    "tools.formCreator.pageNavigation": "Seite {current} von {total}",
    "tools.formCreator.fieldType": "Feldtyp",
    "tools.formCreator.page": "Seite {number}",
    "tools.formCreator.signatureTool": "Unterschrift",
    "tools.formCreator.dateTool": "Datum",
    "tools.formCreator.optionsTab": "Optionen",
    "tools.formCreator.pages": "Seitenanzahl",
    "tools.removeBlankPages.page": "Seite {number}",
    "tools.pdfBooklet.orientationLabel": "Ausrichtung",
    "tools.fontToOutline.optionsTitle": "Optionen",
    "tools.findAndRedact.pageNumber": "Seite {page}",
    "tools.findAndRedact.pageInfo": "Seite {page}",
    "common.buttons.edit": "Bearbeiten",
    "common.globalInvoiceParser.uploadLabel": "Fremdwährungsrechnung (PDF) hochladen",
    "common.globalInvoiceParser.uploadDescription": "Analysiert den Rechnungsbetrag und berechnet den Wechselkurs automatisch lokal, um eine ansprechende lokalisierte Wechselkurs-Ledgerkarte zu rendern.",
    "common.globalInvoiceParser.optionsTitle": "Einstellungen zur globalen Rechnungsumrechnung",
    "common.globalInvoiceParser.processButton": "Rechnungsanalyse & Umrechnung ausführen",
    "common.globalInvoiceParser.successMessage": "Wechselkursbuch erfolgreich auf ausländischer Rechnung aufgestempelt!",
    "common.globalInvoiceParser.previewTitle": "Umrechnungsvorschau für intelligente Rechnungen",
    "common.globalInvoiceParser.convertedSuccess": "Erfolgreich umgerechnet",
    "common.globalInvoiceParser.convertRateApplied": "Ursprünglicher Gesamtbetrag von {original} {currency} wurde lokal mit dem Wechselkurs {rate} erfolgreich umgerechnet.",
    "common.globalInvoiceParser.emptyStateDescription": "Extrahieren Sie Währungsinformationen aus der Rechnung mit einem Klick und rendern Sie lokal eine ansprechende, lokalisierte Wechselkurskarte im modernen Glassmorphismus-Stil.",
    "common.globalInvoiceParser.targetCurrencyLabel": "Zielwährung",
    "common.globalInvoiceParser.customRateLabel": "Benutzerdefinierter Wechselkurs (Optional)",
    "common.globalInvoiceParser.customRatePlaceholder": "z. B. 7,25 (leer lassen, um Echtzeitkurs zu verwenden)",
    "contactPage.methods.email.title": "E-Mail-Adresse",
    "contactPage.form.fields.email.label": "E-Mail-Adresse",
    "tools.pdfMultiTool.uploadDescription": "Ziehen Sie PDF-Dateien hierher oder klicken Sie, um zu suchen. Sie können mehrere Dateien hochladen.",
    "tools.pdfMultiTool.addMoreFiles": "Mehr PDF-Dateien hinzufügen",
    "tools.pdfMultiTool.organize": "Organisieren",
    "tools.pdfMultiTool.rotate": "Rotieren",
    "tools.pdfMultiTool.duplicate": "Duplizieren",
    "tools.pdfMultiTool.addBlank": "Leere Seite hinzufügen",
    "tools.pdfMultiTool.organizeHint": "Ziehen Sie die Seiten per Drag-and-Drop, um die Reihenfolge zu ändern.",
    "tools.pdfMultiTool.deleteHint": "Klicken Sie auf Seiten, um sie zum Löschen zu markieren.",
    "tools.pdfMultiTool.rotateHint": "Klicken Sie auf die Rotationssymbole auf den Seiten oder rotieren Sie alle:",
    "tools.pdfMultiTool.duplicateHint": "Klicken Sie auf das Dupliziersymbol auf den Seiten, um sie zu kopieren.",
    "tools.pdfMultiTool.reset": "Zurücksetzen",
    "tools.pdfMultiTool.undo": "Rückgängig",
    "tools.pdfMultiTool.redo": "Wiederholen",
    "tools.pdfMultiTool.deselectAll": "Auswahl aufheben",
    "tools.pdfMultiTool.exportPDF": "PDF exportieren",
    "tools.pdfMultiTool.downloadSelected": "Ausgewählte herunterladen",
    "tools.pdfMultiTool.addBlankPageTitle": "Leere Seiten hinzufügen",
    "tools.pdfMultiTool.numberOfPages": "Seitenanzahl",
    "tools.pdfMultiTool.insertPosition": "An Position einfügen",
    "tools.pdfMultiTool.processButton": "Änderungen anwenden",
    "tools.pdfMultiTool.successMessage": "PDF erfolgreich verarbeitet! Klicken Sie auf die Download-Schaltfläche, um die Datei zu speichern.",
    "tools.editMetadata.resetButton": "Zurücksetzen",
    "tools.imageToPdf.fitToImage": "An Bildgröße anpassen",
    "tools.imageToPdf.margin": "Rand",
    "tools.imageToPdf.batchMode": "In mehrere PDFs aufteilen",
    "tools.imageToPdf.imagesPerPdf": "Bilder pro PDF",
    "tools.imageToPdf.batchModeHint": "Es werden {pdfCount} PDF-Dateien erstellt, die in einem ZIP-Archiv verpackt werden.",
    "tools.imageToPdf.batchSuccessMessage": "Erfolgreich {pdfCount} PDF-Dateien aus {imageCount} Bildern erstellt! Klicken Sie auf den Download-Button, um Ihr ZIP-Archiv zu speichern.",
    "tools.compressPdf.algorithmLabel": "Komprimierungsalgorithmus",
    "tools.compressPdf.algorithmCondense": "Tiefenkompression",
    "tools.compressPdf.algorithmStandardDesc": "Universelle Standardkomprimierung unter Verwendung von Objektströmen (ausgewogenes Verhältnis zwischen Dateigröße und Qualität).",
    "tools.compressPdf.algorithmCondenseDesc": "Optimiert die interne Struktur des PDFs bei gleichzeitiger Beibehaltung interaktiver Elemente (Kompression unter Beibehaltung der Funktionalität).",
    "tools.compressPdf.algorithmPhotonDesc": "Rasterisiert Seiten in Bilddaten – am besten geeignet für bildlastige PDFs zur maximalen Verkleinerung."
  }
}

with open("d:/NextProject/pdfcraft/scratch/chunk3_splits/translated_split_5.json", "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)
print("Finished writing translated_split_5.json")
