import json

translations = {
  "ja": {
    "tools.formFiller.saveButton": "フォームを保存",
    "tools.formFiller.successMessage": "フォームが正常に保存されました！",
    "tools.removeBlankPages.optionsTitle": "検出オプション",
    "tools.removeBlankPages.successMessage": "白紙ページが正常に削除されました！",
    "tools.removeBlankPages.analyzingPages": "ページを読み込み、情報エントロピーを計算しています...",
    "tools.removeBlankPages.sensitivity": "感度しきい値 (0-100)",
    "tools.removeBlankPages.sensitivityHint": "感度が高いほど判定基準が緩くなり、スキャン時のわずかなノイズや透かしがあるページでも白紙として検出されやすくなります。推奨される白紙ページは、赤い斜線が入った状態でグレーアウト表示されます。各カードをクリックして、強制保持（Force Keep）または強制削除（Force Delete）に上書きできます。",
    "tools.removeBlankPages.autoBlank": "検出された白紙",
    "tools.removeBlankPages.manualKeep": "強制保持",
    "tools.removeBlankPages.manualRemove": "強制削除",
    "tools.removeBlankPages.entropy": "エントロピー",
    "tools.removeBlankPages.noBlankPages": "白紙ページは見つかりませんでした。",
    "tools.tableOfContents.optionsTitle": "目次オプション",
    "tools.tableOfContents.generateButton": "目次を生成する",
    "tools.tableOfContents.successMessage": "目次が正常に生成されました！",
    "tools.tableOfContents.options": "目次オプション",
    "tools.tableOfContents.tocTitle": "目次のタイトル",
    "tools.tableOfContents.fontFamily": "フォントファミリー",
    "tools.tableOfContents.addBookmark": "目次項目をブックマークに追加する",
    "tools.tableOfContents.bookmarkRequired": "このツールは、既存のPDFブックマークからクリック可能な目次を生成します。このツールを使用する前に、PDFにブックマークが含まれていることを確認してください。「ブックマークの編集」ツールを使用してブックマークを追加できます。",
    "tools.tableOfContents.generate": "目次を生成",
    "tools.tableOfContents.success": "目次が正常に生成されました！",
    "tools.pdfToDocx.preserveFormatting": "書式を維持する",
    "tools.pdfToDocx.extractImages": "画像を抽出する",
    "tools.pdfToExcel.detectTables": "表を自動検出する",
    "tools.pdfBooklet.bindingEdge": "綴じ代の位置",
    "tools.emailToPdf.embedAttachments": "PDFに添付ファイルを埋め込む",
    "tools.fontToOutline.preserveSelectableText": "選択可能なテキストを維持する",
    "tools.bookletFoldingSimulator.uploadDescription": "3D折紙シミュレーションを実行するPDFファイルをここにドラッグ＆ドロップしてください。",
    "tools.bookletFoldingSimulator.optionsTitle": "面付け＆折り方オプション",
    "tools.bookletFoldingSimulator.processButton": "面付けを適用する",
    "tools.bookletFoldingSimulator.successMessage": "面付けされた折りシミュレーション用PDFが正常に生成されました！",
    "tools.bookletFoldingSimulator.foldingMode": "折り方スキーム",
    "tools.bookletFoldingSimulator.simulate3D": "3D折紙シミュレーション",
    "tools.bookletFoldingSimulator.sheetProgress": "用紙 {current} / {total}",
    "tools.pdfToSlide.uploadLabel": "学術・ビジネスPDFのアップロード",
    "tools.pdfToSlide.uploadDescription": "PDFをここにドラッグ＆ドロップして、大綱と図表を抽出し、スライドに再構成します。",
    "tools.pdfToSlide.optionsTitle": "スライド再構築オプション",
    "tools.pdfToSlide.processButton": "スライド（PPTX）に再構成する",
    "tools.pdfToSlide.successMessage": "スライドの再構成が成功しました！クリックしてPPTXファイルをダウンロードしてください。",
    "tools.pdfToSlide.outlineExtracting": "ドキュメント構造を分析し、大綱を抽出しています...",
    "tools.pdfToSlide.chartExtracting": "スキャンしてベクターチャートや表を画像として切り出しています...",
    "tools.einkOptimizer.uploadLabel": "スキャンされたPDFのアップロード",
    "tools.einkOptimizer.uploadDescription": "電子ペーパー（e-Ink）のコントラストを最適化するために、PDFの電子書籍をここにドラッグ＆ドロップしてください。",
    "tools.einkOptimizer.optionsTitle": "e-Inkコントラスト最適化",
    "tools.einkOptimizer.processButton": "最適化＆テキストの太字化",
    "tools.einkOptimizer.successMessage": "e-Ink向けPDF最適化が完了しました！ファイルサイズが正常に縮小されました。",
    "tools.einkOptimizer.binarizationThreshold": "大津の二値化しきい値",
    "tools.einkOptimizer.dilationAmount": "文字太字化（膨張）半径",
    "tools.certCryptor.uploadLabel": "保護するPDFのアップロード",
    "tools.certCryptor.uploadDescription": "PDFファイルをここにドラッグ＆ドロップして、3Dワックスシールとデジタル証明書ロックを適用します。",
    "tools.certCryptor.optionsTitle": "ワックスシール＆証明書セキュリティ",
    "tools.certCryptor.processButton": "ワックスシール署名を実行する",
    "tools.certCryptor.successMessage": "3Dワックスシール捺印および証明書暗号化が正常に適用されました！",
    "tools.certCryptor.waxColor": "ワックスシールのスタイル（色）",
    "tools.certCryptor.signCoordinates": "署名の配置座標",
    "tools.passportIdComposer.uploadLabel": "身分証画像のアップロード",
    "tools.passportIdComposer.uploadDescription": "パスポートや身分証明書の両面（表・裏）の画像をここにドラッグ＆ドロップして、A4のコピー（面付け）を作成します。",
    "tools.passportIdComposer.optionsTitle": "身分証面付けオプション",
    "tools.passportIdComposer.processButton": "A4レイアウトに合成する",
    "tools.passportIdComposer.successMessage": "パスポート/身分証明書が正常に合成されました！",
    "tools.annotationExporter.uploadLabel": "注釈付きPDFのアップロード",
    "tools.annotationExporter.uploadDescription": "PDFファイルをここにドラッグ＆ドロップして、ハイライト、コメント、アウトラインノートを抽出します。",
    "tools.annotationExporter.optionsTitle": "注釈抽出オプション",
    "tools.annotationExporter.processButton": "ノートを抽出する",
    "tools.annotationExporter.successMessage": "PDFの注釈が正常に抽出されました！",
    "tools.batchWatermarkRemover.uploadLabel": "透かし入りPDFのアップロード",
    "tools.batchWatermarkRemover.uploadDescription": "PDFファイルをここにドラッグ＆ドロップして、背景の透かしを物理的に一括消去します。",
    "tools.batchWatermarkRemover.optionsTitle": "透かし削除オプション",
    "tools.batchWatermarkRemover.processButton": "透かしを消去する",
    "tools.batchWatermarkRemover.successMessage": "背景の透かしが正常に物理消去されました！",
    "tools.smartDataRedactor.uploadLabel": "黒塗り（墨消し）するPDFのアップロード",
    "tools.smartDataRedactor.uploadDescription": "PDFファイルをここにドラッグ＆ドロップして、個人情報や機密データを自動でスキャンし黒塗り（墨消し）します。",
    "tools.smartDataRedactor.optionsTitle": "スマート黒塗りルール",
    "tools.smartDataRedactor.processButton": "機密データを黒塗りする",
    "tools.smartDataRedactor.successMessage": "PDFの個人情報・機密データが正常に黒塗り（墨消し）されました！",
    "tools.bookmarksAutoGenerator.uploadDescription": "PDFファイルをここにドラッグ＆ドロップして、ドキュメント構造からしおり（ブックマーク）を自動生成します。",
    "tools.bookmarksAutoGenerator.optionsTitle": "しおり自動生成オプション",
    "tools.bookmarksAutoGenerator.processButton": "しおりを推論・挿入する",
    "tools.bookmarksAutoGenerator.successMessage": "PDFのしおり（ブックマーク）構造が正常に挿入されました！"
  },
  "ko": {
    "tools.formFiller.saveButton": "양식 저장",
    "tools.formFiller.successMessage": "양식이 성공적으로 저장되었습니다!",
    "tools.removeBlankPages.optionsTitle": "감지 옵션",
    "tools.removeBlankPages.successMessage": "빈 페이지가 성공적으로 제거되었습니다!",
    "tools.removeBlankPages.analyzingPages": "페이지를 읽고 정보 엔트로피를 계산하는 중...",
    "tools.removeBlankPages.sensitivity": "민감도 임계값 (0-100)",
    "tools.removeBlankPages.sensitivityHint": "민감도가 높을수록 기준이 완화되어 스캔 시 발생하는 미세한 노이즈나 워터마크가 있는 페이지도 빈 페이지로 더 쉽게 감지됩니다. 권장 빈 페이지는 빨간색 사선이 있는 회색 카드로 표시됩니다. 각 카드를 직접 클릭하여 강제 유지(Force Keep) 또는 강제 삭제(Force Delete)로 설정을 변경할 수 있습니다.",
    "tools.removeBlankPages.autoBlank": "감지된 빈 페이지",
    "tools.removeBlankPages.manualKeep": "강제 유지",
    "tools.removeBlankPages.manualRemove": "강제 삭제",
    "tools.removeBlankPages.entropy": "엔트로피",
    "tools.removeBlankPages.noBlankPages": "빈 페이지가 발견되지 않았습니다.",
    "tools.tableOfContents.optionsTitle": "목차 옵션",
    "tools.tableOfContents.generateButton": "목차 생성",
    "tools.tableOfContents.successMessage": "목차가 성공적으로 생성되었습니다!",
    "tools.tableOfContents.options": "목차 옵션",
    "tools.tableOfContents.tocTitle": "목차 제목",
    "tools.tableOfContents.fontFamily": "글꼴",
    "tools.tableOfContents.addBookmark": "목차 항목을 북마크에 추가",
    "tools.tableOfContents.bookmarkRequired": "이 도구는 기존 PDF 북마크에서 클릭 가능한 목차를 생성합니다. 이 도구를 사용하기 전에 PDF에 북마크가 있는지 확인하십시오. 「북마크 편집」 도구를 사용하여 북마크를 추가할 수 있습니다.",
    "tools.tableOfContents.generate": "목차 생성",
    "tools.tableOfContents.success": "목차가 성공적으로 생성되었습니다!",
    "tools.pdfToDocx.preserveFormatting": "서식 유지",
    "tools.pdfToDocx.extractImages": "이미지 추출",
    "tools.pdfToExcel.detectTables": "표 자동 감지",
    "tools.pdfBooklet.bindingEdge": "제본 여백 방향",
    "tools.emailToPdf.embedAttachments": "PDF에 첨부 파일 포함",
    "tools.fontToOutline.preserveSelectableText": "선택 가능한 텍스트 유지",
    "tools.bookletFoldingSimulator.uploadDescription": "3D 접지 시뮬레이션을 진행할 PDF 파일을 여기에 드래그 앤 드롭하십시오.",
    "tools.bookletFoldingSimulator.optionsTitle": "터잡기(임포지션) 및 접지 옵션",
    "tools.bookletFoldingSimulator.processButton": "터잡기 적용",
    "tools.bookletFoldingSimulator.successMessage": "터잡기가 적용된 접지 시뮬레이션용 PDF가 성공적으로 생성되었습니다!",
    "tools.bookletFoldingSimulator.foldingMode": "접지 형태",
    "tools.bookletFoldingSimulator.simulate3D": "3D 접지 시뮬레이션",
    "tools.bookletFoldingSimulator.sheetProgress": "인쇄용지 {current} / {total}",
    "tools.pdfToSlide.uploadLabel": "학술/비즈니스 PDF 업로드",
    "tools.pdfToSlide.uploadDescription": "여기에 PDF를 드래그 앤 드롭하여 슬라이드 재구성을 위한 아웃라인 및 차트를 추출하십시오.",
    "tools.pdfToSlide.optionsTitle": "슬라이드 재구성 옵션",
    "tools.pdfToSlide.processButton": "슬라이드(PPTX)로 재구성",
    "tools.pdfToSlide.successMessage": "슬라이드 재구성이 성공했습니다! 클릭하여 PPTX 파일을 다운로드하십시오.",
    "tools.pdfToSlide.outlineExtracting": "문서 구조 분석 및 아웃라인 추출 중...",
    "tools.pdfToSlide.chartExtracting": "벡터 차트와 표를 스캔하여 이미지로 분리하는 중...",
    "tools.einkOptimizer.uploadLabel": "스캔된 PDF 업로드",
    "tools.einkOptimizer.uploadDescription": "전자잉크(e-Ink) 화면 대비 최적화를 위해 PDF 전자책을 여기에 드래그 앤 드롭하십시오.",
    "tools.einkOptimizer.optionsTitle": "e-Ink 대비 최적화",
    "tools.einkOptimizer.processButton": "최적화 및 텍스트 굵게",
    "tools.einkOptimizer.successMessage": "e-Ink PDF 최적화가 완료되었습니다! 파일 크기가 성공적으로 줄어들었습니다.",
    "tools.einkOptimizer.binarizationThreshold": "오츠 이진화 임계값",
    "tools.einkOptimizer.dilationAmount": "글씨 굵기 확장(팽창) 반경",
    "tools.certCryptor.uploadLabel": "보안을 적용할 PDF 업로드",
    "tools.certCryptor.uploadDescription": "여기에 PDF 파일을 드래그 앤 드롭하여 3D 실링 왁스 서명 및 인증서 잠금을 적용하십시오.",
    "tools.certCryptor.optionsTitle": "실링 왁스 서명 및 인증서 보안",
    "tools.certCryptor.processButton": "실링 왁스 서명 실행",
    "tools.certCryptor.successMessage": "3D 실링 왁스 씰 적용 및 인증서 기반 암호화가 성공적으로 적용되었습니다!",
    "tools.certCryptor.waxColor": "실링 왁스 스타일(색상)",
    "tools.certCryptor.signCoordinates": "서명 배치 위치",
    "tools.passportIdComposer.uploadLabel": "신분증 이미지 업로드",
    "tools.passportIdComposer.uploadDescription": "A4 복사본(터잡기)을 생성하려면 여권 또는 신분증의 앞면과 뒷면 이미지를 여기에 드래그 앤 드롭하십시오.",
    "tools.passportIdComposer.optionsTitle": "신분증 터잡기 옵션",
    "tools.passportIdComposer.processButton": "A4 레이아웃 합성",
    "tools.passportIdComposer.successMessage": "여권/신분증이 성공적으로 합성되었습니다!",
    "tools.annotationExporter.uploadLabel": "주석이 포함된 PDF 업로드",
    "tools.annotationExporter.uploadDescription": "여기에 PDF를 드래그 앤 드롭하여 하이라이트, 코멘트 및 아웃라인 노트를 추출하십시오.",
    "tools.annotationExporter.optionsTitle": "주석 추출 옵션",
    "tools.annotationExporter.processButton": "노트 추출",
    "tools.annotationExporter.successMessage": "PDF 주석이 성공적으로 추출되었습니다!",
    "tools.batchWatermarkRemover.uploadLabel": "워터마크가 포함된 PDF 업로드",
    "tools.batchWatermarkRemover.uploadDescription": "여기에 PDF를 드래그 앤 드롭하여 배경 워터마크를 물리적으로 일괄 지우십시오.",
    "tools.batchWatermarkRemover.optionsTitle": "워터마크 제거 옵션",
    "tools.batchWatermarkRemover.processButton": "워터마크 일괄 삭제",
    "tools.batchWatermarkRemover.successMessage": "배경 워터마크가 성공적으로 물리적 일괄 삭제되었습니다!",
    "tools.smartDataRedactor.uploadLabel": "개인정보를 삭제할 PDF 업로드",
    "tools.smartDataRedactor.uploadDescription": "여기에 PDF를 드래그 앤 드롭하여 개인정보 및 민감 데이터를 자동으로 스캔하고 비식별화(마스킹) 처리하십시오.",
    "tools.smartDataRedactor.optionsTitle": "스마트 비식별화 규칙",
    "tools.smartDataRedactor.processButton": "민감 데이터 마스킹 처리",
    "tools.smartDataRedactor.successMessage": "PDF 개인정보 및 민감 데이터가 성공적으로 마스킹 처리되었습니다!",
    "tools.bookmarksAutoGenerator.uploadDescription": "여기에 PDF를 드래그 앤 드롭하여 문서 구조에 맞춰 북마크를 자동으로 생성하십시오.",
    "tools.bookmarksAutoGenerator.optionsTitle": "북마크 자동 생성 옵션",
    "tools.bookmarksAutoGenerator.processButton": "북마크 유추 및 삽입",
    "tools.bookmarksAutoGenerator.successMessage": "북마크 구조가 PDF 아웃라인에 성공적으로 삽입되었습니다!"
  },
  "de": {
    "tools.formFiller.saveButton": "Formular speichern",
    "tools.formFiller.successMessage": "Formular erfolgreich gespeichert!",
    "tools.removeBlankPages.optionsTitle": "Erkennungsoptionen",
    "tools.removeBlankPages.successMessage": "Leere Seiten erfolgreich entfernt!",
    "tools.removeBlankPages.analyzingPages": "Seiten werden gelesen und die Informationsentropie wird berechnet...",
    "tools.removeBlankPages.sensitivity": "Empfindlichkeitsschwellenwert (0-100)",
    "tools.removeBlankPages.sensitivityHint": "Je höher die Empfindlichkeit, desto toleranter ist das Verfahren. Seiten mit geringem Scanrauschen oder Wasserzeichen werden leichter als leer erkannt. Vorgeschlagene leere Seiten werden ausgegraut mit einem roten diagonalen Balken dargestellt. Klicken Sie direkt auf die Karten, um die Auswahl manuell zu überschreiben: Beibehalten erzwingen oder Löschen erzwingen.",
    "tools.removeBlankPages.autoBlank": "Leer erkannt",
    "tools.removeBlankPages.manualKeep": "Erzwungenes Behalten",
    "tools.removeBlankPages.manualRemove": "Erzwungenes Löschen",
    "tools.removeBlankPages.entropy": "Entropie",
    "tools.removeBlankPages.noBlankPages": "Keine leeren Seiten gefunden.",
    "tools.tableOfContents.optionsTitle": "TOC-Optionen",
    "tools.tableOfContents.generateButton": "Inhaltsverzeichnis generieren",
    "tools.tableOfContents.successMessage": "Inhaltsverzeichnis erfolgreich generiert!",
    "tools.tableOfContents.options": "Inhaltsverzeichnis-Optionen",
    "tools.tableOfContents.tocTitle": "TOC-Titel",
    "tools.tableOfContents.fontFamily": "Schriftart",
    "tools.tableOfContents.addBookmark": "TOC-Eintrag zu Lesezeichen hinzufügen",
    "tools.tableOfContents.bookmarkRequired": "Dieses Tool generiert ein anklickbares Inhaltsverzeichnis aus vorhandenen PDF-Lesezeichen. Bitte stellen Sie sicher, dass Ihr PDF Lesezeichen enthält, bevor Sie dieses Tool verwenden. Sie können Lesezeichen mit dem Tool 'Lesezeichen bearbeiten' hinzufügen.",
    "tools.tableOfContents.generate": "Inhaltsverzeichnis generieren",
    "tools.tableOfContents.success": "Inhaltsverzeichnis erfolgreich generiert!",
    "tools.pdfToDocx.preserveFormatting": "Formatierung beibehalten",
    "tools.pdfToDocx.extractImages": "Bilder extrahieren",
    "tools.pdfToExcel.detectTables": "Tabellen automatisch erkennen",
    "tools.pdfBooklet.bindingEdge": "Bindungskante",
    "tools.emailToPdf.embedAttachments": "Anhänge in PDF einbetten",
    "tools.fontToOutline.preserveSelectableText": "Auswählbaren Text beibehalten",
    "tools.bookletFoldingSimulator.uploadDescription": "Ziehen Sie eine PDF-Datei hierher für die 3D-Falzsimulation.",
    "tools.bookletFoldingSimulator.optionsTitle": "Ausschieß- & Falzoptionen",
    "tools.bookletFoldingSimulator.processButton": "Ausschießen anwenden",
    "tools.bookletFoldingSimulator.successMessage": "Ausgeschossenes Falz-PDF erfolgreich generiert!",
    "tools.bookletFoldingSimulator.foldingMode": "Falzschema",
    "tools.bookletFoldingSimulator.simulate3D": "3D-Falzsimulation",
    "tools.bookletFoldingSimulator.sheetProgress": "Bogen {current} von {total}",
    "tools.pdfToSlide.uploadLabel": "Wissenschaftliches/Geschäftliches PDF hochladen",
    "tools.pdfToSlide.uploadDescription": "Ziehen Sie ein PDF hierher, um Gliederungen und Diagramme für die Folienrekonstruktion zu extrahieren.",
    "tools.pdfToSlide.optionsTitle": "Folienrekonstruktions-Optionen",
    "tools.pdfToSlide.processButton": "Folien rekonstruieren (PPTX)",
    "tools.pdfToSlide.successMessage": "Folienrekonstruktion erfolgreich! Klicken Sie hier, um die PPTX-Datei herunterzuladen.",
    "tools.pdfToSlide.outlineExtracting": "Dokumentenstruktur wird analysiert und Gliederungen werden extrahiert...",
    "tools.pdfToSlide.chartExtracting": "Vektordiagramme und Tabellen werden gescannt und als Bilder isoliert...",
    "tools.einkOptimizer.uploadLabel": "Gescanntes PDF hochladen",
    "tools.einkOptimizer.uploadDescription": "Ziehen Sie Ihr PDF-E-Book hierher, um den Kontrast für e-Ink-Displays zu optimieren.",
    "tools.einkOptimizer.optionsTitle": "e-Ink Kontrast-Optimierer",
    "tools.einkOptimizer.processButton": "Optimieren & Text fetten",
    "tools.einkOptimizer.successMessage": "e-Ink-PDF-Optimierung abgeschlossen! Dateigröße erfolgreich verringert.",
    "tools.einkOptimizer.binarizationThreshold": "Otsu-Binarisierungsschwellenwert",
    "tools.einkOptimizer.dilationAmount": "Radius für Zeichenfettung (Dilation)",
    "tools.certCryptor.uploadLabel": "Zu sicherndes PDF hochladen",
    "tools.certCryptor.uploadDescription": "Ziehen Sie Ihr PDF hierher, um ein 3D-Siegellack-Siegel und eine Zertifikatssperre anzuwenden.",
    "tools.certCryptor.optionsTitle": "Siegellack & Zertifikatssicherheit",
    "tools.certCryptor.processButton": "Siegellack-Signatur ausführen",
    "tools.certCryptor.successMessage": "3D-Siegellack-Aufdruck und zertifikatsbasierte Verschlüsselung erfolgreich angewendet!",
    "tools.certCryptor.waxColor": "Siegellack-Stil",
    "tools.certCryptor.signCoordinates": "Signaturplatzierung",
    "tools.passportIdComposer.uploadLabel": "Ausweisbilder hochladen",
    "tools.passportIdComposer.uploadDescription": "Ziehen Sie Vorder- und Rückseite von Reisepass/Ausweis hierher, um eine A4-Kopie zu erstellen.",
    "tools.passportIdComposer.optionsTitle": "Ausweis-Ausschussoptionen",
    "tools.passportIdComposer.processButton": "A4-Layout zusammenstellen",
    "tools.passportIdComposer.successMessage": "Reisepass/Ausweis erfolgreich zusammengestellt!",
    "tools.annotationExporter.uploadLabel": "Annotiertes PDF hochladen",
    "tools.annotationExporter.uploadDescription": "Ziehen Sie Ihr PDF hierher, um Markierungen, Kommentare und Notizstrukturen zu extrahieren.",
    "tools.annotationExporter.optionsTitle": "Anmerkungsextraktions-Optionen",
    "tools.annotationExporter.processButton": "Notizbuch extrahieren",
    "tools.annotationExporter.successMessage": "PDF-Anmerkungen erfolgreich extrahiert!",
    "tools.batchWatermarkRemover.uploadLabel": "PDF mit Wasserzeichen hochladen",
    "tools.batchWatermarkRemover.uploadDescription": "Ziehen Sie Ihr PDF hierher, um Wasserzeichen aus dem Hintergrund physisch zu entfernen.",
    "tools.batchWatermarkRemover.optionsTitle": "Wasserzeichenentfernungs-Optionen",
    "tools.batchWatermarkRemover.processButton": "Wasserzeichen entfernen",
    "tools.batchWatermarkRemover.successMessage": "Wasserzeichen erfolgreich physisch entfernt!",
    "tools.smartDataRedactor.uploadLabel": "Zu schwärzendes PDF hochladen",
    "tools.smartDataRedactor.uploadDescription": "Ziehen Sie das PDF hierher, um sensible Daten automatisch zu scannen und zu schwärzen.",
    "tools.smartDataRedactor.optionsTitle": "Intelligente Schwärzungsregeln",
    "tools.smartDataRedactor.processButton": "Sensible Daten schwärzen",
    "tools.smartDataRedactor.successMessage": "PDF-Datenschwärzung erfolgreich durchgeführt!",
    "tools.bookmarksAutoGenerator.uploadDescription": "Ziehen Sie Ihr PDF hierher, um Lesezeichen automatisch aus der Struktur zu generieren.",
    "tools.bookmarksAutoGenerator.optionsTitle": "Optionen zur Lesezeichengenerierung",
    "tools.bookmarksAutoGenerator.processButton": "Lesezeichen ableiten & einfügen",
    "tools.bookmarksAutoGenerator.successMessage": "Lesezeichen erfolgreich in die PDF-Outlinestruktur injiziert!"
  }
}

with open("d:/NextProject/pdfcraft/scratch/chunk3_splits/translated_split_2.json", "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)
print("Finished writing translated_split_2.json")
