import json

translations = {
  "ja": {
    "tools.changePermissions.allowHighQualityPrinting": "高品質な印刷を許可する",
    "tools.changePermissions.allowHighQualityPrintingDesc": "ユーザーは高解像度での印刷ができます",
    "tools.changePermissions.allowModifying": "変更を許可する",
    "tools.changePermissions.allowModifyingDesc": "ユーザーはドキュメントの編集ができます",
    "tools.changePermissions.allowCopying": "コピーを許可する",
    "tools.changePermissions.allowCopyingDesc": "ユーザーはテキストや画像のコピーができます",
    "tools.changePermissions.allowAnnotating": "注釈の追加を許可する",
    "tools.changePermissions.allowAnnotatingDesc": "ユーザーはコメントや注釈の追加ができます",
    "tools.changePermissions.allowFillingForms": "フォーム入力を許可する",
    "tools.changePermissions.allowFillingFormsDesc": "ユーザーはフォームフィールドへの入力ができます",
    "tools.changePermissions.allowAccessibility": "アクセシビリティを許可する",
    "tools.changePermissions.allowAccessibilityDesc": "スクリーンリーダーがコンテンツにアクセスできます",
    "tools.changePermissions.allowAssembly": "アセンブリを許可する",
    "tools.changePermissions.allowAssemblyDesc": "ユーザーはページの挿入、削除、回転ができます",
    "tools.changePermissions.applyButton": "権限を適用する",
    "tools.changePermissions.successMessage": "アクセス権限が正常に更新されました！",
    "tools.changePermissions.successHint": "権限制限を完全に適用するには、オーナーパスワードを設定してPDFを暗号化してください。",
    "tools.changePermissions.invalidPassword": "入力された現在のパスワードが正しくありません。確認してもう一度お試しください。",
    "tools.changePermissions.passwordRequired": "このPDFはパスワードで保護されています。処理を進めるには現在のパスワードを入力してください。",
    "tools.fixPageSize.optionsTitle": "ページサイズオプション",
    "tools.fixPageSize.targetSize": "目標ページサイズ",
    "tools.fixPageSize.width": "幅 (ポイント)",
    "tools.fixPageSize.height": "高さ (ポイント)",
    "tools.fixPageSize.scaleMode": "コンテンツの縮尺モード",
    "tools.fixPageSize.scaleFit": "合わせる (Fit)",
    "tools.fixPageSize.scaleFill": "埋める (Fill)",
    "tools.fixPageSize.scaleStretch": "引き伸ばす (Stretch)",
    "tools.fixPageSize.scaleCenter": "中央配置 (Center)",
    "tools.fixPageSize.scaleFitDesc": "縦横比を維持しながら、ページ内に収まるようにコンテンツを縮小・拡大します",
    "tools.fixPageSize.scaleFillDesc": "ページ全体を埋めるようにコンテンツを拡大・縮小します（端が切り取られる場合があります）",
    "tools.fixPageSize.scaleStretchDesc": "ページサイズに正確に一致するようにコンテンツを引き伸ばします",
    "tools.fixPageSize.scaleCenterDesc": "拡大縮小せず、コンテンツを中央に配置します",
    "tools.fixPageSize.orientation": "ページの向き",
    "tools.fixPageSize.maintainAspectRatio": "縦横比を維持する",
    "tools.fixPageSize.applyButton": "ページサイズを修正する",
    "tools.fixPageSize.successMessage": "ページサイズが正常に修正されました！",
    "tools.bookmark.normal": "標準",
    "tools.bookmark.bold": "太字",
    "tools.bookmark.italic": "斜体",
    "tools.bookmark.boldItalic": "太字＆斜体",
    "tools.bookmark.setToCurrentPage": "現在のページに設定",
    "tools.watermark.optionsTitle": "透かしオプション",
    "tools.watermark.textWatermark": "テキスト透かし",
    "tools.watermark.imageWatermark": "画像透かし",
    "tools.watermark.watermarkImage": "透かし画像 (PNG/JPG)",
    "tools.watermark.enterText": "透かしとして表示するテキストを入力してください。",
    "tools.watermark.selectImage": "透かし用の画像ファイルを選択してください。",
    "tools.watermark.unsupportedImage": "サポートされていない画像形式です。PNGまたはJPGを使用してください。",
    "tools.watermark.failed": "透かしの追加に失敗しました。",
    "tools.watermark.addButton": "透かしを追加する",
    "tools.watermark.successMessage": "透かしが正常に追加されました！",
    "tools.headerFooter.headerTitle": "ヘッダー",
    "tools.headerFooter.footerTitle": "フッター",
    "tools.headerFooter.previewHint": "プレビューを表示するにはヘッダーまたはフッターのテキストを入力してください",
    "tools.headerFooter.addButton": "ヘッダー＆フッターを追加",
    "tools.headerFooter.successMessage": "ヘッダーとフッターが正常に追加されました！",
    "tools.invertColors.invertButton": "色を反転する",
    "tools.invertColors.successMessage": "色の反転が正常に完了しました！",
    "tools.backgroundColor.applyButton": "背景色を適用する",
    "tools.backgroundColor.successMessage": "背景色が正常に適用されました！",
    "tools.textColor.modeLabel": "テキストタイプ",
    "tools.textColor.modeDark": "暗いテキスト（明るい背景）",
    "tools.textColor.modeLight": "明るいテキスト（暗い背景）",
    "tools.textColor.thresholdLabel": "輝度しきい値",
    "tools.textColor.thresholdHint": "影響を受けるピクセルを制御するために調整します",
    "tools.textColor.applyButton": "テキスト色を適用する",
    "tools.textColor.successMessage": "テキスト色が正常に適用されました！",
    "tools.stamps.instructionsTitle": "スタンプの追加方法",
    "tools.stamps.instruction1": "上のツールバーにあるスタンプツール（画像アイコン）をクリックします",
    "tools.stamps.instruction2": "「画像を追加」をクリックしてスタンプ画像をアップロードします",
    "tools.stamps.instruction3": "PDF内のスタンプを配置したい場所をクリックします",
    "tools.stamps.instruction4": "ドラッグしてスタンプのサイズ変更や位置調整を行います",
    "tools.stamps.instruction5": "完了したら、以下の「スタンプ付きPDFを保存」をクリックします",
    "tools.stamps.saveButton": "スタンプ付きPDFを保存",
    "tools.stamps.viewerNotReady": "ビューアの準備ができていません。PDFがロードされるまでお待ちください。",
    "tools.stamps.saveFailed": "スタンプ付きPDFの保存に失敗しました。もう一度お試しください。",
    "tools.stamps.successMessage": "スタンプが正常に追加されました！",
    "tools.removeAnnotations.optionsTitle": "削除オプション",
    "tools.removeAnnotations.successMessage": "注釈が正常に削除されました！",
    "tools.formFiller.uploadDescription": "ここにPDFフォームをドラッグ＆ドロップしてください。"
  },
  "ko": {
    "tools.changePermissions.allowHighQualityPrinting": "고품질 인쇄 허용",
    "tools.changePermissions.allowHighQualityPrintingDesc": "사용자가 고해상도로 인쇄할 수 있습니다",
    "tools.changePermissions.allowModifying": "수정 허용",
    "tools.changePermissions.allowModifyingDesc": "사용자가 문서를 편집할 수 있습니다",
    "tools.changePermissions.allowCopying": "복사 허용",
    "tools.changePermissions.allowCopyingDesc": "사용자가 텍스트 및 이미지를 복사할 수 있습니다",
    "tools.changePermissions.allowAnnotating": "주석 작성 허용",
    "tools.changePermissions.allowAnnotatingDesc": "사용자가 주석 및 코멘트를 추가할 수 있습니다",
    "tools.changePermissions.allowFillingForms": "양식 작성 허용",
    "tools.changePermissions.allowFillingFormsDesc": "사용자가 양식 필드를 작성할 수 있습니다",
    "tools.changePermissions.allowAccessibility": "접근성 허용",
    "tools.changePermissions.allowAccessibilityDesc": "스크린 리더가 콘텐츠에 접근할 수 있습니다",
    "tools.changePermissions.allowAssembly": "페이지 구성 허용",
    "tools.changePermissions.allowAssemblyDesc": "사용자가 페이지를 삽입, 삭제 또는 회전할 수 있습니다",
    "tools.changePermissions.applyButton": "권한 적용",
    "tools.changePermissions.successMessage": "권한이 성공적으로 업데이트되었습니다!",
    "tools.changePermissions.successHint": "전체 권한 제한을 적용하려면 소유자 비밀번호로 PDF를 암호화하십시오.",
    "tools.changePermissions.invalidPassword": "입력한 현재 비밀번호가 올바르지 않습니다. 다시 확인 후 시도하십시오.",
    "tools.changePermissions.passwordRequired": "이 PDF는 비밀번호로 보호되어 있습니다. 진행하려면 현재 비밀번호를 입력하십시오.",
    "tools.fixPageSize.optionsTitle": "페이지 크기 옵션",
    "tools.fixPageSize.targetSize": "대상 페이지 크기",
    "tools.fixPageSize.width": "너비 (포인트)",
    "tools.fixPageSize.height": "높이 (포인트)",
    "tools.fixPageSize.scaleMode": "콘텐츠 크기 조정",
    "tools.fixPageSize.scaleFit": "맞춤 (Fit)",
    "tools.fixPageSize.scaleFill": "채움 (Fill)",
    "tools.fixPageSize.scaleStretch": "늘림 (Stretch)",
    "tools.fixPageSize.scaleCenter": "가운데 (Center)",
    "tools.fixPageSize.scaleFitDesc": "종횡비를 유지하면서 페이지 크기에 맞게 콘텐츠를 축소 또는 확대합니다",
    "tools.fixPageSize.scaleFillDesc": "페이지를 꽉 채우도록 콘텐츠 크기를 조정합니다 (가장자리가 잘릴 수 있음)",
    "tools.fixPageSize.scaleStretchDesc": "콘텐츠를 늘려 페이지 크기에 정확히 맞춥니다",
    "tools.fixPageSize.scaleCenterDesc": "크기 조정 없이 콘텐츠를 중앙에 배치합니다",
    "tools.fixPageSize.orientation": "페이지 방향",
    "tools.fixPageSize.maintainAspectRatio": "종횡비 유지",
    "tools.fixPageSize.applyButton": "페이지 크기 수정",
    "tools.fixPageSize.successMessage": "페이지 크기가 성공적으로 수정되었습니다!",
    "tools.bookmark.normal": "보통",
    "tools.bookmark.bold": "굵게",
    "tools.bookmark.italic": "기울임꼴",
    "tools.bookmark.boldItalic": "굵게 및 기울임꼴",
    "tools.bookmark.setToCurrentPage": "현재 페이지로 설정",
    "tools.watermark.optionsTitle": "워터마크 옵션",
    "tools.watermark.textWatermark": "텍스트 워터마크",
    "tools.watermark.imageWatermark": "이미지 워터마크",
    "tools.watermark.watermarkImage": "워터마크 이미지 (PNG/JPG)",
    "tools.watermark.enterText": "워터마크에 사용할 텍스트를 입력하십시오.",
    "tools.watermark.selectImage": "워터마크용 이미지 파일을 선택하십시오.",
    "tools.watermark.unsupportedImage": "지원되지 않는 이미지 형식입니다. PNG 또는 JPG를 사용하십시오.",
    "tools.watermark.failed": "워터마크 추가에 실패했습니다.",
    "tools.watermark.addButton": "워터마크 추가",
    "tools.watermark.successMessage": "워터마크가 성공적으로 추가되었습니다!",
    "tools.headerFooter.headerTitle": "머리글",
    "tools.headerFooter.footerTitle": "바닥글",
    "tools.headerFooter.previewHint": "미리보기를 보려면 머리글 또는 바닥글 텍스트를 입력하십시오",
    "tools.headerFooter.addButton": "머리글 및 바닥글 추가",
    "tools.headerFooter.successMessage": "머리글과 바닥글이 성공적으로 추가되었습니다!",
    "tools.invertColors.invertButton": "색상 반전",
    "tools.invertColors.successMessage": "색상이 성공적으로 반전되었습니다!",
    "tools.backgroundColor.applyButton": "배경색 적용",
    "tools.backgroundColor.successMessage": "배경색이 성공적으로 적용되었습니다!",
    "tools.textColor.modeLabel": "텍스트 유형",
    "tools.textColor.modeDark": "어두운 텍스트 (밝은 배경)",
    "tools.textColor.modeLight": "밝은 텍스트 (어두운 배경)",
    "tools.textColor.thresholdLabel": "밝기 임계값",
    "tools.textColor.thresholdHint": "적용할 픽셀 범위를 조절하기 위해 조절합니다",
    "tools.textColor.applyButton": "텍스트 색상 적용",
    "tools.textColor.successMessage": "텍스트 색상이 성공적으로 적용되었습니다!",
    "tools.stamps.instructionsTitle": "도장/스탬프 추가 방법",
    "tools.stamps.instruction1": "상단 도구 모음에서 스탬프 도구(이미지 아이콘)를 클릭합니다",
    "tools.stamps.instruction2": "「이미지 추가」를 클릭하여 스탬프 이미지를 업로드합니다",
    "tools.stamps.instruction3": "PDF 내에서 스탬프를 배치할 위치를 클릭합니다",
    "tools.stamps.instruction4": "드래그하여 스탬프 크기 조절 및 위치를 재조정합니다",
    "tools.stamps.instruction5": "완료되면 아래의 「스탬프 적용된 PDF 저장」을 클릭합니다",
    "tools.stamps.saveButton": "스탬프 적용된 PDF 저장",
    "tools.stamps.viewerNotReady": "뷰어가 준비되지 않았습니다. PDF가 로드될 때까지 기다려주십시오.",
    "tools.stamps.saveFailed": "스탬프가 적용된 PDF 저장에 실패했습니다. 다시 시도하십시오.",
    "tools.stamps.successMessage": "스탬프가 성공적으로 추가되었습니다!",
    "tools.removeAnnotations.optionsTitle": "제거 옵션",
    "tools.removeAnnotations.successMessage": "주석이 성공적으로 제거되었습니다!",
    "tools.formFiller.uploadDescription": "여기에 PDF 양식 파일을 드래그 앤 드롭하십시오."
  },
  "de": {
    "tools.changePermissions.allowHighQualityPrinting": "Hochwertiges Drucken erlauben",
    "tools.changePermissions.allowHighQualityPrintingDesc": "Benutzer können mit hoher Auflösung drucken",
    "tools.changePermissions.allowModifying": "Änderungen erlauben",
    "tools.changePermissions.allowModifyingDesc": "Benutzer können das Dokument bearbeiten",
    "tools.changePermissions.allowCopying": "Kopieren erlauben",
    "tools.changePermissions.allowCopyingDesc": "Benutzer können Text und Bilder kopieren",
    "tools.changePermissions.allowAnnotating": "Kommentieren erlauben",
    "tools.changePermissions.allowAnnotatingDesc": "Benutzer können Kommentare und Anmerkungen hinzufügen",
    "tools.changePermissions.allowFillingForms": "Formularausfüllung erlauben",
    "tools.changePermissions.allowFillingFormsDesc": "Benutzer können Formularfelder ausfüllen",
    "tools.changePermissions.allowAccessibility": "Barrierefreiheit erlauben",
    "tools.changePermissions.allowAccessibilityDesc": "Screenreader können auf den Inhalt zugreifen",
    "tools.changePermissions.allowAssembly": "Dokumentenzusammenstellung erlauben",
    "tools.changePermissions.allowAssemblyDesc": "Benutzer können Seiten einfügen, löschen oder rotieren",
    "tools.changePermissions.applyButton": "Berechtigungen anwenden",
    "tools.changePermissions.successMessage": "Berechtigungen erfolgreich aktualisiert!",
    "tools.changePermissions.successHint": "Für eine vollständige Durchsetzung der Berechtigungen verschlüsseln Sie das PDF mit einem Berechtigungskennwort.",
    "tools.changePermissions.invalidPassword": "Das eingegebene aktuelle Kennwort ist falsch. Bitte überprüfen Sie es und versuchen Sie es erneut.",
    "tools.changePermissions.passwordRequired": "Dieses PDF ist passwortgeschützt. Bitte geben Sie das aktuelle Kennwort ein, um fortzufahren.",
    "tools.fixPageSize.optionsTitle": "Seitengrößenoptionen",
    "tools.fixPageSize.targetSize": "Zielseitengröße",
    "tools.fixPageSize.width": "Breite (Punkte)",
    "tools.fixPageSize.height": "Höhe (Punkte)",
    "tools.fixPageSize.scaleMode": "Inhaltsskalierung",
    "tools.fixPageSize.scaleFit": "Einpassen",
    "tools.fixPageSize.scaleFill": "Ausfüllen",
    "tools.fixPageSize.scaleStretch": "Strecken",
    "tools.fixPageSize.scaleCenter": "Zentrieren",
    "tools.fixPageSize.scaleFitDesc": "Skaliert den Inhalt so, dass er auf die Seite passt, unter Beibehaltung des Seitenverhältnisses",
    "tools.fixPageSize.scaleFillDesc": "Skaliert den Inhalt so, dass er die Seite ausfüllt. Kanten können abgeschnitten werden",
    "tools.fixPageSize.scaleStretchDesc": "Streckt den Inhalt, um die Seite exakt auszufüllen",
    "tools.fixPageSize.scaleCenterDesc": "Zentriert den Inhalt ohne Skalierung",
    "tools.fixPageSize.orientation": "Seitenausrichtung",
    "tools.fixPageSize.maintainAspectRatio": "Seitenverhältnis beibehalten",
    "tools.fixPageSize.applyButton": "Seitengrößen anpassen",
    "tools.fixPageSize.successMessage": "Seitengrößen erfolgreich angepasst!",
    "tools.bookmark.normal": "Standard",
    "tools.bookmark.bold": "Fett",
    "tools.bookmark.italic": "Kursiv",
    "tools.bookmark.boldItalic": "Fett & Kursiv",
    "tools.bookmark.setToCurrentPage": "Auf aktuelle Seite setzen",
    "tools.watermark.optionsTitle": "Wasserzeichenoptionen",
    "tools.watermark.textWatermark": "Text-Wasserzeichen",
    "tools.watermark.imageWatermark": "Bild-Wasserzeichen",
    "tools.watermark.watermarkImage": "Wasserzeichen-Bild (PNG/JPG)",
    "tools.watermark.enterText": "Bitte geben Sie den Text für das Wasserzeichen ein.",
    "tools.watermark.selectImage": "Bitte wählen Sie eine Bilddatei für das Wasserzeichen aus.",
    "tools.watermark.unsupportedImage": "Nicht unterstütztes Bildformat. Bitte verwenden Sie PNG oder JPG.",
    "tools.watermark.failed": "Wasserzeichen konnte nicht hinzugefügt werden.",
    "tools.watermark.addButton": "Wasserzeichen hinzufügen",
    "tools.watermark.successMessage": "Wasserzeichen erfolgreich hinzugefügt!",
    "tools.headerFooter.headerTitle": "Kopfzeile",
    "tools.headerFooter.footerTitle": "Fußzeile",
    "tools.headerFooter.previewHint": "Geben Sie Kopf- oder Fußzeilentext ein, um die Vorschau anzuzeigen",
    "tools.headerFooter.addButton": "Kopf- & Fußzeile hinzufügen",
    "tools.headerFooter.successMessage": "Kopf- & Fußzeile erfolgreich hinzugefügt!",
    "tools.invertColors.invertButton": "Farben umkehren",
    "tools.invertColors.successMessage": "Farben erfolgreich umgekehrt!",
    "tools.backgroundColor.applyButton": "Hintergrundfarbe anwenden",
    "tools.backgroundColor.successMessage": "Hintergrundfarbe erfolgreich angewendet!",
    "tools.textColor.modeLabel": "Texttyp",
    "tools.textColor.modeDark": "Dunkler Text (heller Hintergrund)",
    "tools.textColor.modeLight": "Heller Text (dunkler Hintergrund)",
    "tools.textColor.thresholdLabel": "Helligkeitsschwellenwert",
    "tools.textColor.thresholdHint": "Anpassen, um zu steuern, welche Pixel betroffen sind",
    "tools.textColor.applyButton": "Textfarbe anwenden",
    "tools.textColor.successMessage": "Textfarbe erfolgreich angewendet!",
    "tools.stamps.instructionsTitle": "So fügen Sie Stempel hinzu",
    "tools.stamps.instruction1": "Klicken Sie auf das Stempel-Werkzeug (Bild-Symbol) in der Symbolleiste oben",
    "tools.stamps.instruction2": "Klicken Sie auf „Bild hinzufügen“, um Ihr Stempelbild hochzuladen",
    "tools.stamps.instruction3": "Klicken Sie auf die Stelle im PDF, an der Sie den Stempel platzieren möchten",
    "tools.stamps.instruction4": "Ziehen Sie, um die Größe des Stempels zu ändern oder ihn neu zu positionieren",
    "tools.stamps.instruction5": "Klicken Sie unten auf „Gestempeltes PDF speichern“, wenn Sie fertig sind",
    "tools.stamps.saveButton": "Gestempeltes PDF speichern",
    "tools.stamps.viewerNotReady": "Viewer nicht bereit. Bitte warten Sie, bis das PDF geladen ist.",
    "tools.stamps.saveFailed": "Gestempeltes PDF konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.",
    "tools.stamps.successMessage": "Stempel erfolgreich hinzugefügt!",
    "tools.removeAnnotations.optionsTitle": "Entfernungsoptionen",
    "tools.removeAnnotations.successMessage": "Anmerkungen erfolgreich entfernt!",
    "tools.formFiller.uploadDescription": "Ziehen Sie ein PDF-Formular hierher."
  }
}

with open("d:/NextProject/pdfcraft/scratch/chunk3_splits/translated_split_1.json", "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)
print("Finished writing translated_split_1.json")
