import json

translations = {
  "ja": {
    "tools.batchBarcodeInjector.uploadDescription": "QRコードやバーコードを一括挿入（スタンプ）するには、ここにPDFをドラッグ＆ドロップしてください。",
    "tools.batchBarcodeInjector.optionsTitle": "バーコード精密スタンプオプション",
    "tools.batchBarcodeInjector.processButton": "バーコードの一括スタンプを実行",
    "tools.batchBarcodeInjector.successMessage": "資産管理用バーコード/QRコードが正常に一括挿入されました！",
    "tools.signatureInkOptimizer.uploadLabel": "手書き署名/印章写真のアップロード",
    "tools.signatureInkOptimizer.uploadDescription": "署名や印章の写真から、背景を透過させたPNGインクレイヤーを抽出します。",
    "tools.signatureInkOptimizer.optionsTitle": "インク浄化フィルター設定",
    "tools.signatureInkOptimizer.processButton": "手書き署名の背景を透過処理する",
    "tools.signatureInkOptimizer.successMessage": "手書き署名・印章の背景のノイズ除去と透過処理が正常に完了しました！",
    "tools.deadLinkDebugger.uploadLabel": "リンクデバッグ対象PDFのアップロード",
    "tools.deadLinkDebugger.uploadDescription": "PDFファイルをここにドラッグ＆ドロップして、内部および外部ハイパーリンクを調査します。",
    "tools.deadLinkDebugger.optionsTitle": "ハイパーリンク調査＆リダイレクト設定",
    "tools.deadLinkDebugger.processButton": "全ハイパーリンクの検証を開始",
    "tools.deadLinkDebugger.successMessage": "すべてのハイパーリンクの検証と修復が正常に完了しました！",
    "tools.interactiveTocGenerator.uploadDescription": "PDFファイルをここにドラッグ＆ドロップして、インタラクティブ（クリック可能）な目次を自動生成・追加します。",
    "tools.interactiveTocGenerator.optionsTitle": "インタラクティブ目次挿入オプション",
    "tools.interactiveTocGenerator.processButton": "インタラクティブな目次を生成する",
    "tools.interactiveTocGenerator.successMessage": "クリック可能な目次ページと双方向の移動リンクが正常に挿入されました！",
    "tools.globalInvoiceParser.uploadLabel": "海外インボイス（外貨発票）のアップロード",
    "tools.globalInvoiceParser.uploadDescription": "外貨建てのインボイスPDFをここにドラッグ＆ドロップして、為替レートの換算と記帳カードのスタンプを行います。",
    "tools.globalInvoiceParser.optionsTitle": "外貨換算レートオプション",
    "tools.globalInvoiceParser.processButton": "インボイスの翻訳と為替換算を実行",
    "tools.globalInvoiceParser.successMessage": "インボイスの翻訳と現地通貨換算の元帳スタンプが正常に適用されました！",
    "tools.watermark.rangeOdd": "奇数ページのみ",
    "tools.watermark.rangeEven": "偶数ページのみ",
    "tools.watermark.rangeCustom": "カスタム範囲（ページ指定）",
    "tools.watermark.rangePlaceholder": "例: 1, 3, 5-10",
    "tools.watermark.previewNote": "プレビュー生成速度向上のため最初のページのみ表示しています",
    "tools.watermark.previewGenerating": "プレビューを生成中...",
    "common.navigation.workflow": "ワークフロー",
    "common.options.auto": "自動",
    "common.comparePdfs.originalVersion": " (オリジナル)",
    "common.editPdf.annFreeText": "テキスト",
    "common.nUpPdf.orientationAuto": "自動",
    "common.removeBlankPages.resetBtn": "手動変更をクリア",
    "faqPage.title": "よくあるご質問 (FAQ)",
    "faqPage.subtitle": "{brand} に関するよくある質問の回答を探す",
    "faqPage.searchPlaceholder": "よくあるご質問を検索...",
    "faqPage.noResults": "検索条件に一致するご質問は見つかりませんでした。",
    "faqPage.expandAll": "すべて展開",
    "faqPage.collapseAll": "すべて折りたたむ",
    "faqPage.categories.all": "すべて",
    "faqPage.categories.general": "一般",
    "faqPage.categories.privacy": "プライバシー＆セキュリティ",
    "faqPage.categories.features": "機能について",
    "faqPage.categories.technical": "技術面について",
    "faqPage.categories.languages": "言語設定",
    "faqPage.sections.general.whatIs.question": "PDFCraftとは何ですか？",
    "faqPage.sections.general.isFree.question": "PDFCraftは本当に無料ですか？",
    "faqPage.sections.general.isFree.answer": "はい、PDFCraftは完全に無料でご利用いただけます。隠れた費用や有料プラン、会員登録などは一切ありません。すべての機能をすべての人にご利用いただけます。",
    "faqPage.sections.general.account.question": "アカウントを作成する必要がありますか？",
    "faqPage.sections.general.account.answer": "いいえ、PDFCraftを使用するためにアカウントを作成したり登録したりする必要はありません。ウェブサイトにアクセスするだけで、すぐに任意のツールをご利用いただけます。",
    "faqPage.sections.privacy.uploaded.question": "アップロードしたファイルはサーバーに保存されますか？",
    "faqPage.sections.privacy.uploaded.answer": "いいえ、お客様のファイルがサーバーにアップロードされることは一切ありません。すべてのPDF処理は、JavaScriptとWebAssemblyを使用してお客様のブラウザ内でローカルに行われます。ファイルがデバイスから送信されることはありません。",
    "faqPage.sections.privacy.safe.question": "機密性の高いドキュメントでPDFCraftを使用しても安全ですか？",
    "faqPage.sections.privacy.safe.answer": "はい、PDFCraftはプライバシーを最優先に設計されています。すべての処理がブラウザ内でローカルに実行されるため、機密ドキュメントはデバイス内に残り、インターネットを介して送信されることはありません。",
    "faqPage.sections.privacy.storage.question": "処理完了後、ファイルはどうなりますか？",
    "faqPage.sections.privacy.storage.answer": "ファイルは処理中、ブラウザのメモリに一時的にのみ保存されます。ブラウザのタブを閉じるか他のページに移動すると、すべてのファイルデータは自動的に消去されます。弊社がお客様のファイルを保管することは一切ありません。",
    "faqPage.sections.features.operations.question": "どのようなPDF操作を実行できますか？",
    "faqPage.sections.features.operations.answer": "PDFCraftは、結合、分割、圧縮、各種変換（画像・テキスト・JSONへの/からの変換）、編集、注釈、署名、透かし追加、暗号化/復号化、OCRなど、67以上のツールを提供しています。",
    "faqPage.sections.features.merge.question": "複数のPDFファイルを結合できますか？",
    "faqPage.sections.features.merge.answer": "はい、複数のPDFファイルを1つのファイルに結合できます。「PDF結合」ツールを使用し、ファイルをアップロードして希望の順序に並べ替え、「結合」ボタンをクリックしてください。",
    "faqPage.sections.features.images.question": "画像をPDFに変換できますか？",
    "faqPage.sections.features.images.answer": "はい、PDFCraftはさまざまな画像形式（JPG、PNG、WebP、BMP、TIFF、SVG、HEIC）のPDFへの変換に対応しています。1枚だけでなく、複数の画像を一度に変換することも可能です。",
    "faqPage.sections.features.edit.question": "PDF内のテキストを直接編集することはできますか？",
    "faqPage.sections.features.edit.answer": "PDFCraftは、ハイライト、テキストの追加、図形、画像、署名の挿入などの注釈・編集ツールを提供しています。詳細な注釈やマークアップ機能には、「PDF編集」ツールをご利用ください。",
    "faqPage.sections.technical.browsers.question": "サポートされているブラウザは何ですか？",
    "faqPage.sections.technical.browsers.answer": "PDFCraftは、Chrome、Firefox、Safari、Edgeを含むすべての主要なモダンブラウザに対応しています。快適にご利用いただくために、ブラウザの最新バージョンをご使用いただくことをお勧めします。",
    "faqPage.sections.technical.sizeLimit.question": "ファイルサイズに制限はありますか？",
    "faqPage.sections.technical.sizeLimit.answer": "ほとんどのツールは最大100MBまでのファイルに対応しており、結合や圧縮などの一部のツールでは最大500MBまで対応しています。これらの制限は、ブラウザ内での動作をスムーズに維持するために設けられています。",
    "faqPage.sections.technical.slow.question": "大容量ファイルの場合、処理が遅くなるのはなぜですか？",
    "faqPage.sections.technical.slow.answer": "すべての処理がお使いのブラウザ内で行われるため、処理のパフォーマンスはお使いのデバイスのスペックに依存します。大容量ファイルはより多くのメモリとCPU性能を必要とします。快適に処理するために、他のブラウザのタブやバックグラウンドアプリを閉じてからお試しください。",
    "faqPage.sections.technical.offline.question": "PDFCraftはオフラインでも動作しますか？",
    "faqPage.sections.technical.offline.answer": "現在、PDFCraftを読み込むためにはインターネット接続が必要です。ただし、アプリが一度完全に読み込まれれば、PDFの処理自体はローカルで行われるため、インターネット接続は必要ありません。",
    "faqPage.sections.languages.supported.question": "サポートされている言語は何ですか？",
    "faqPage.sections.languages.supported.answer": "PDFCraftは9言語に対応しています：英語、日本語、韓国語、スペイン語、フランス語、ドイツ語、中国語、ポルトガル語、アラビア語（右から左へのRTL表記対応）。",
    "faqPage.sections.languages.change.question": "言語を変更するにはどうすればよいですか？",
    "faqPage.sections.languages.change.answer": "ヘッダー右上にある言語セレクターから言語を変更できます。選択した設定は保存され、次回の訪問時にも自動的に適用されます。",
    "faqPage.cta.title": "まだご不明な点がありますか？",
    "faqPage.cta.description": "お探しの回答が見つからない場合は、お気軽にお問い合わせください。"
  },
  "ko": {
    "tools.batchBarcodeInjector.uploadDescription": "QR 코드 또는 바코드를 일괄 배치로 추가하려면 여기에 PDF 파일을 드래그 앤 드롭하십시오.",
    "tools.batchBarcodeInjector.optionsTitle": "바코드 고정밀 배치 주입 옵션",
    "tools.batchBarcodeInjector.processButton": "바코드 일괄 주입 실행",
    "tools.batchBarcodeInjector.successMessage": "자산용 바코드/QR 코드가 성공적으로 일괄 추가되었습니다!",
    "tools.signatureInkOptimizer.uploadLabel": "手필 서명/인장 사진 업로드",
    "tools.signatureInkOptimizer.uploadDescription": "서명 사진을 드래그 앤 드롭하여 투명한 PNG 서명 레이어로 노이즈를 제거하여 淨化합니다.",
    "tools.signatureInkOptimizer.optionsTitle": "필적 필터 및 淨化 설정",
    "tools.signatureInkOptimizer.processButton": "순수 투명 서명/인장 이미지로 변환",
    "tools.signatureInkOptimizer.successMessage": "손글씨 서명/도장 사진의 배경 투명 처리가 완벽히 완료되었습니다!",
    "tools.deadLinkDebugger.uploadLabel": "링크 검출용 PDF 업로드",
    "tools.deadLinkDebugger.uploadDescription": "PDF를 드래그 앤 드롭하여 내부 및 외부 하이퍼링크를 분석하고 테스트하십시오.",
    "tools.deadLinkDebugger.optionsTitle": "하이퍼링크 상태 검사 및 리디렉션 옵션",
    "tools.deadLinkDebugger.processButton": "전체 하이퍼링크 분석 시작",
    "tools.deadLinkDebugger.successMessage": "하이퍼링크 검사 및 복원이 성공적으로 완료되었습니다!",
    "tools.interactiveTocGenerator.uploadDescription": "대화형(클릭 가능한) 목차 페이지를 자동으로 구성하고 삽입하려면 여기에 PDF를 드래그 앤 드롭하십시오.",
    "tools.interactiveTocGenerator.optionsTitle": "상호 작용형 목차 삽입 매개변수",
    "tools.interactiveTocGenerator.processButton": "상호 작용형 목차 자동 생성",
    "tools.interactiveTocGenerator.successMessage": "클릭 시 해당 페이지로 바로 이동하는 목차와 양방향 앵커 링크가 성공적으로 주입되었습니다!",
    "tools.globalInvoiceParser.uploadLabel": "외화 송장(인보이스) PDF 업로드",
    "tools.globalInvoiceParser.uploadDescription": "외화 송장 PDF를 여기에 드래그 앤 드롭하여 자동으로 환율 변환 및 로컬 장부 카드를 생성하십시오.",
    "tools.globalInvoiceParser.optionsTitle": "글로벌 송장 외환 변환 옵션",
    "tools.globalInvoiceParser.processButton": "송장 자동 번역 및 환산 실행",
    "tools.globalInvoiceParser.successMessage": "외화 송장의 번역 및 로컬 통화 환산 장부 스탬프 적용이 성공적으로 완료되었습니다!",
    "tools.watermark.rangeOdd": "홀수 페이지",
    "tools.watermark.rangeEven": "짝수 페이지",
    "tools.watermark.rangeCustom": "사용자 정의 페이지 범위",
    "tools.watermark.rangePlaceholder": "예: 1, 3, 5-10",
    "tools.watermark.previewNote": "로딩 성능 최적화를 위해 첫 번째 페이지만 미리보기로 표시합니다",
    "tools.watermark.previewGenerating": "미리보기 생성 중...",
    "common.navigation.workflow": "워크플로우",
    "common.options.auto": "자동",
    "common.comparePdfs.originalVersion": " (원본)",
    "common.editPdf.annFreeText": "텍스트",
    "common.nUpPdf.orientationAuto": "자동",
    "common.removeBlankPages.resetBtn": "수동 변경 사항 초기화",
    "faqPage.title": "자주 묻는 질문 (FAQ)",
    "faqPage.subtitle": "{brand}에 관해 자주 묻는 질문들의 답변을 확인해 보세요.",
    "faqPage.searchPlaceholder": "자주 묻는 질문 검색...",
    "faqPage.noResults": "검색어와 일치하는 질문을 찾을 수 없습니다.",
    "faqPage.expandAll": "모두 펼치기",
    "faqPage.collapseAll": "모두 접기",
    "faqPage.categories.all": "전체",
    "faqPage.categories.general": "일반",
    "faqPage.categories.privacy": "개인정보 보호 및 보안",
    "faqPage.categories.features": "도구 기능",
    "faqPage.categories.technical": "기술 지원",
    "faqPage.categories.languages": "언어 설정",
    "faqPage.sections.general.whatIs.question": "PDFCraft는 무엇인가요?",
    "faqPage.sections.general.isFree.question": "PDFCraft는 정말 무료인가요?",
    "faqPage.sections.general.isFree.answer": "네, PDFCraft는 완전히 무료로 사용할 수 있습니다. 숨겨진 비용이나 프리미엄 요금제, 회원 가입이 필요하지 않습니다. 모든 기능을 누구나 제한 없이 이용 가능합니다.",
    "faqPage.sections.general.account.question": "회원가입이나 계정 생성이 필요한가요?",
    "faqPage.sections.general.account.answer": "아니요, PDFCraft를 사용하기 위해 계정을 생성하거나 등록할 필요가 없습니다. 웹사이트를 방문하여 즉시 원하는 도구를 시작해 보세요.",
    "faqPage.sections.privacy.uploaded.question": "제 파일이 서버로 업로드되나요?",
    "faqPage.sections.privacy.uploaded.answer": "아니요, 파일은 서버로 절대 업로드되지 않습니다. 모든 PDF 처리는 JavaScript와 WebAssembly를 사용하여 웹 브라우저 내에서 안전하게 로컬로 진행됩니다. 파일이 장치 외부로 절대 송출되지 않습니다.",
    "faqPage.sections.privacy.safe.question": "민감한 문서에 PDFCraft를 사용해도 안전한가요?",
    "faqPage.sections.privacy.safe.answer": "네, PDFCraft는 철저하게 개인정보 보호를 염두에 두고 설계되었습니다. 모든 처리가 브라우저 내에서 직접 이루어지므로, 중요한 문서가 사용자 장치에 그대로 유지되며 인터넷을 통해 전송되지 않습니다.",
    "faqPage.sections.privacy.storage.question": "처리 완료 후 파일들은 어떻게 처리되나요?",
    "faqPage.sections.privacy.storage.answer": "파일은 처리되는 동안에 브라우저 메모리에 일시적으로만 저장됩니다. 브라우저 탭을 닫거나 다른 페이지로 이동하면 파일 데이터가 자동으로 완전히 삭제됩니다. 당사는 어떠한 파일도 보관하지 않습니다.",
    "faqPage.sections.features.operations.question": "어떤 PDF 작업들을 지원하나요?",
    "faqPage.sections.features.operations.answer": "PDFCraft는 병합, 분할, 압축, 변환(이미지, 텍스트, JSON 등 상호 변환), 편집, 주석, 서명, 워터마크 추가, 암호화/해제, OCR 등을 포함한 67개 이상의 다양한 무료 도구를 제공합니다.",
    "faqPage.sections.features.merge.question": "여러 PDF 파일을 하나로 합칠 수 있나요?",
    "faqPage.sections.features.merge.answer": "네, 여러 PDF 파일을 하나로 합칠 수 있습니다. 「PDF 병합」 도구를 사용하여 파일을 업로드하고 원하는 순서로 정렬한 다음 병합을 누르십시오.",
    "faqPage.sections.features.images.question": "이미지를 PDF로 변환할 수 있나요?",
    "faqPage.sections.features.images.answer": "네, PDFCraft는 JPG, PNG, WebP, BMP, TIFF, SVG, HEIC 등의 이미지를 PDF로 변환하는 작업을 지원합니다. 단일 또는 여러 이미지를 한 번에 변환할 수 있습니다.",
    "faqPage.sections.features.edit.question": "PDF 안의 글자를 직접 수정할 수 있나요?",
    "faqPage.sections.features.edit.answer": "PDFCraft는 텍스트 추가, 형광펜 표시, 도형 삽입, 서명 삽입 등의 주석 추가 및 편집 도구를 지원합니다. 전체 텍스트 편집 수준의 주석 작성 및 표시는 「PDF 편집기」 도구를 이용하시면 더욱 편리합니다.",
    "faqPage.sections.technical.browsers.question": "어떤 웹 브라우저를 지원하나요?",
    "faqPage.sections.technical.browsers.answer": "PDFCraft는 Chrome, Firefox, Safari, Edge 등 모든 모던 브라우저에서 잘 작동합니다. 최상의 경험을 위해 브라우저를 항상 최신 버전으로 업데이트하여 사용하시는 것을 권장합니다.",
    "faqPage.sections.technical.sizeLimit.question": "업로드할 수 있는 파일 용량 제한이 있나요?",
    "faqPage.sections.technical.sizeLimit.answer": "대부분의 도구는 최대 100MB 크기의 파일을 지원하며, 병합 및 압축 등 일부 도구는 최대 500MB까지 지원합니다. 이 제한은 브라우저 상에서 안정적인 웹 페이지 처리 속도를 유지하기 위함입니다.",
    "faqPage.sections.technical.slow.question": "용량이 큰 파일은 처리 속도가 느린가요?",
    "faqPage.sections.technical.slow.answer": "모든 작업이 브라우저에서 실행되므로, 컴퓨터 또는 휴대폰의 사양에 따라 성능이 좌우됩니다. 큰 파일은 더 많은 메모리와 CPU 연산 성능이 필요합니다. 최적의 결과를 얻으려면 사용하지 않는 다른 탭이나 프로그램을 종료해 주십시오.",
    "faqPage.sections.technical.offline.question": "인터넷이 연결되지 않은 상태에서도 작동하나요?",
    "faqPage.sections.technical.offline.answer": "현재로서는 PDFCraft 웹 앱을 처음 로드하기 위해 네트워크 연결이 필요합니다. 하지만 앱이 한 번 완전히 로드되면, 실제 PDF 변환 및 처리 작업은 모두 로컬에서 수행되므로 오프라인에서도 진행할 수 있습니다.",
    "faqPage.sections.languages.supported.question": "지원하는 언어 목록은 무엇인가요?",
    "faqPage.sections.languages.supported.answer": "PDFCraft는 영어, 일본어, 한국어, 스페인어, 프랑스어, 독일어, 중국어, 포르투갈어 및 아랍어(우측에서 좌측으로 쓰는 RTL 지원) 등 총 9개국 언어로 맞춤 제공됩니다.",
    "faqPage.sections.languages.change.question": "언어 설정을 어떻게 변경하나요?",
    "faqPage.sections.languages.change.answer": "상단 헤더에 있는 언어 선택 드롭다운을 사용하여 언제든지 변경할 수 있습니다. 변경된 설정은 브라우저에 저장되어 다음 방문 시에도 동일하게 적용됩니다.",
    "faqPage.cta.title": "아직 궁금한 점이 해결되지 않으셨나요?",
    "faqPage.cta.description": "원하시는 질문과 답변을 찾기 어려우신 경우, 주저하지 마시고 당사 고객 서비스로 문의해 주시기 바랍니다."
  },
  "de": {
    "tools.batchBarcodeInjector.uploadDescription": "Ziehen Sie das PDF hierher, um QR-/Barcodes im Stapelverfahren aufzustempeln.",
    "tools.batchBarcodeInjector.optionsTitle": "Optionen für hochpräzise Barcode-Stempel",
    "tools.batchBarcodeInjector.processButton": "Barcodes stapelweise einfügen",
    "tools.batchBarcodeInjector.successMessage": "Anlagen-Barcodes/QR-Codes erfolgreich stapelweise eingefügt!",
    "tools.signatureInkOptimizer.uploadLabel": "Unterschriften-/Stempelfoto hochladen",
    "tools.signatureInkOptimizer.uploadDescription": "Ziehen Sie Unterschriftenfotos hierher, um die Hintergrundgeräusche zu bereinigen und eine transparente PNG-Tintenschicht zu extrahieren.",
    "tools.signatureInkOptimizer.optionsTitle": "Tintenreiniger-Filtereinstellungen",
    "tools.signatureInkOptimizer.processButton": "Transparente handschriftliche Unterschriften/Stempel extrahieren",
    "tools.signatureInkOptimizer.successMessage": "Hintergrundgeräusche von handschriftlichen Unterschriften/Stempeln erfolgreich gefiltert und bereinigt!",
    "tools.deadLinkDebugger.uploadLabel": "PDF zum Link-Debugging hochladen",
    "tools.deadLinkDebugger.uploadDescription": "Ziehen Sie das PDF hierher, um interne und externe Hyperlinks auf fehlerhafte Weiterleitungen zu untersuchen.",
    "tools.deadLinkDebugger.optionsTitle": "Hyperlink-Überprüfungs- & Umleitungseinstellungen",
    "tools.deadLinkDebugger.processButton": "Globale Hyperlink-Überprüfung starten",
    "tools.deadLinkDebugger.successMessage": "Hyperlinks erfolgreich verifiziert und repariert!",
    "tools.interactiveTocGenerator.uploadDescription": "Ziehen Sie das PDF hierher, um automatisch ein interaktives (anklickbares) Inhaltsverzeichnis zu generieren und einzufügen.",
    "tools.interactiveTocGenerator.optionsTitle": "Parameter für interaktives Inhaltsverzeichnis",
    "tools.interactiveTocGenerator.processButton": "Interaktives Inhaltsverzeichnis generieren",
    "tools.interactiveTocGenerator.successMessage": "Interaktive Inhaltsverzeichnisseite und bidirektionale Sprunganker erfolgreich injiziert!",
    "tools.globalInvoiceParser.uploadLabel": "Ausländische Rechnung (PDF) hochladen",
    "tools.globalInvoiceParser.uploadDescription": "Ziehen Sie die PDF-Rechnung hierher, um den Betrag automatisch in Ihre lokale Währung umzurechnen und ein Ledger-Dokument zu stempeln.",
    "tools.globalInvoiceParser.optionsTitle": "Währungsumrechnungs-Optionen",
    "tools.globalInvoiceParser.processButton": "Rechnung übersetzen und Währung umrechnen",
    "tools.globalInvoiceParser.successMessage": "Fremdwährungsrechnung erfolgreich übersetzt und lokales Währungsledger-Siegel aufgestempelt!",
    "tools.watermark.rangeOdd": "Ungerade Seiten",
    "tools.watermark.rangeEven": "Gerade Seiten",
    "tools.watermark.rangeCustom": "Benutzerdefinierter Seitenbereich",
    "tools.watermark.rangePlaceholder": "z. B. 1, 3, 5-10",
    "tools.watermark.previewNote": "Aus Leistungsgründen wird nur die erste Seite als Vorschau geladen",
    "tools.watermark.previewGenerating": "Vorschau wird generiert...",
    "common.navigation.workflow": "Workflow",
    "common.options.auto": "Auto",
    "common.comparePdfs.originalVersion": " (Original)",
    "common.editPdf.annFreeText": "Text",
    "common.nUpPdf.orientationAuto": "Auto",
    "common.removeBlankPages.resetBtn": "Manuelle Änderungen zurücksetzen",
    "faqPage.title": "Häufig gestellte Fragen (FAQ)",
    "faqPage.subtitle": "Finden Sie Antworten auf häufig gestellte Fragen zu {brand}",
    "faqPage.searchPlaceholder": "FAQs durchsuchen...",
    "faqPage.noResults": "Keine FAQs gefunden, die Ihrer Suche entsprechen.",
    "faqPage.expandAll": "Alle erweitern",
    "faqPage.collapseAll": "Alle zuklappen",
    "faqPage.categories.all": "Alle",
    "faqPage.categories.general": "Allgemein",
    "faqPage.categories.privacy": "Datenschutz & Sicherheit",
    "faqPage.categories.features": "Funktionen",
    "faqPage.categories.technical": "Technische Details",
    "faqPage.categories.languages": "Spracheinstellungen",
    "faqPage.sections.general.whatIs.question": "Was ist PDFCraft?",
    "faqPage.sections.general.isFree.question": "Ist PDFCraft wirklich kostenlos?",
    "faqPage.sections.general.isFree.answer": "Ja, PDFCraft ist absolut kostenlos nutzbar. Es gibt keine versteckten Kosten, keine Premium-Stufen und keine Registrierungspflicht. Alle Funktionen stehen jedem zur Verfügung.",
    "faqPage.sections.general.account.question": "Muss ich ein Konto erstellen?",
    "faqPage.sections.general.account.answer": "Nein, Sie müssen kein Konto erstellen oder sich registrieren, um PDFCraft zu nutzen. Besuchen Sie einfach die Website und verwenden Sie sofort jedes gewünschte Tool.",
    "faqPage.sections.privacy.uploaded.question": "Werden meine hochgeladenen Dateien auf einem Server gespeichert?",
    "faqPage.sections.privacy.uploaded.answer": "Nein, Ihre Dateien werden niemals auf einen Server hochgeladen. Die gesamte PDF-Verarbeitung erfolgt lokal in Ihrem Browser unter Verwendung von JavaScript und WebAssembly. Ihre Dateien verlassen Ihr Gerät niemals.",
    "faqPage.sections.privacy.safe.question": "Ist es sicher, PDFCraft für sensible Dokumente zu verwenden?",
    "faqPage.sections.privacy.safe.answer": "Ja, PDFCraft wurde mit Blick auf den Datenschutz entwickelt. Da die gesamte Verarbeitung lokal in Ihrem Browser erfolgt, verbleiben Ihre sensiblen Dokumente auf Ihrem Gerät und werden niemals über das Internet übertragen.",
    "faqPage.sections.privacy.storage.question": "Was passiert mit meinen Dateien nach der Verarbeitung?",
    "faqPage.sections.privacy.storage.answer": "Ihre Dateien werden während der Verarbeitung vorübergehend im Speicher Ihres Browsers abgelegt. Sobald Sie den Browser-Tab schließen oder die Seite verlassen, werden alle Dateidaten automatisch gelöscht. Wir speichern keine Ihrer Dateien.",
    "faqPage.sections.features.operations.question": "Welche PDF-Operationen kann ich durchführen?",
    "faqPage.sections.features.operations.answer": "PDFCraft bietet über 67 Werkzeuge, darunter: Zusammenführen, Aufteilen, Komprimieren, Konvertieren (in/aus Bildern, Text, JSON), Bearbeiten, Annotieren, Signieren, Wasserzeichen hinzufügen, Verschlüsseln/Entschlüsseln, OCR und viele mehr.",
    "faqPage.sections.features.merge.question": "Kann ich mehrere PDF-Dateien zusammenführen?",
    "faqPage.sections.features.merge.answer": "Ja, Sie können mehrere PDF-Dateien zu einer zusammenführen. Verwenden Sie einfach das Tool 'PDF zusammenführen', laden Sie Ihre Dateien hoch, ordnen Sie sie in der gewünschten Reihenfolge an und klicken Sie auf 'Zusammenführen'.",
    "faqPage.sections.features.images.question": "Kann ich Bilder in PDF konvertieren?",
    "faqPage.sections.features.images.answer": "Ja, PDFCraft unterstützt das Konvertieren verschiedener Bildformate (JPG, PNG, WebP, BMP, TIFF, SVG, HEIC) in PDF. Sie können einzelne oder mehrere Bilder gleichzeitig konvertieren.",
    "faqPage.sections.features.edit.question": "Kann ich den Text in einer PDF direkt bearbeiten?",
    "faqPage.sections.features.edit.answer": "PDFCraft bietet Anmerkungs- und Bearbeitungswerkzeuge wie Hervorhebungen, Hinzufügen von Text, Formen, Bildern und Unterschriften. Für eine umfassende Textbearbeitung bietet das PDF-Editor-Werkzeug umfangreiche Anmerkungsfunktionen.",
    "faqPage.sections.technical.browsers.question": "Welche Browser werden unterstützt?",
    "faqPage.sections.technical.browsers.answer": "PDFCraft funktioniert in allen modernen Browsern, einschließlich Chrome, Firefox, Safari und Edge. Wir empfehlen, die neueste Version Ihres Browsers zu verwenden, um die beste Benutzererfahrung zu erzielen.",
    "faqPage.sections.technical.sizeLimit.question": "Gibt es eine Begrenzung der Dateigröße?",
    "faqPage.sections.technical.sizeLimit.answer": "Die meisten Tools unterstützen Dateien mit einer Größe von bis zu 100 MB. Einige Tools wie 'Zusammenführen' und 'Komprimieren' unterstützen bis zu 500 MB. Diese Grenzen sind erforderlich, um eine flüssige Leistung in Ihrem Browser zu gewährleisten.",
    "faqPage.sections.technical.slow.question": "Warum ist die Verarbeitung bei großen Dateien langsam?",
    "faqPage.sections.technical.slow.answer": "Da die Verarbeitung vollständig in Ihrem Browser erfolgt, hängt die Leistung von den Kapazitäten Ihres Geräts ab. Große Dateien erfordern mehr Arbeitsspeicher und Rechenleistung. Schließen Sie für optimale Ergebnisse andere Browser-Tabs und Anwendungen.",
    "faqPage.sections.technical.offline.question": "Funktioniert PDFCraft offline?",
    "faqPage.sections.technical.offline.answer": "Derzeit benötigt PDFCraft eine Internetverbindung, um die Anwendung zu laden. Sobald diese jedoch geladen ist, findet die PDF-Verarbeitung selbst lokal statt und benötigt keine Verbindung mehr.",
    "faqPage.sections.languages.supported.question": "Welche Sprachen werden unterstützt?",
    "faqPage.sections.languages.supported.answer": "PDFCraft ist in 9 Sprachen verfügbar: Englisch, Japanisch, Koreanisch, Spanisch, Französisch, Deutsch, Chinesisch, Portugiesisch und Arabisch (mit RTL-Unterstützung).",
    "faqPage.sections.languages.change.question": "Wie ändere ich die Sprache?",
    "faqPage.sections.languages.change.answer": "Sie können die Sprache über die Sprachauswahl in der Kopfzeile ändern. Ihre bevorzugte Einstellung wird für zukünftige Besuche gespeichert.",
    "faqPage.cta.title": "Haben Sie noch Fragen?",
    "faqPage.cta.description": "Sie können die gesuchte Antwort nicht finden? Zögern Sie nicht, uns direkt zu kontaktieren."
  }
}

with open("d:/NextProject/pdfcraft/scratch/chunk3_splits/translated_split_3.json", "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)
print("Finished writing translated_split_3.json")
